// ═══════════════════════════════════════════════════════════════════════════
// ARIZONA LEADS LOADER — Bulk import AZ cannabis businesses into Ryan's CRM
// Run from browser console or integrate into admin panel
// ═══════════════════════════════════════════════════════════════════════════

import type { UniversalContact } from '../lib/contactCapture';

export const AZ_LEADS: UniversalContact[] = [
  // ═══════════════════ DISPENSARIES ═══════════════════
  { name: "Curaleaf Arizona", businessName: "Curaleaf Holdings Inc.", phone: "(480) 739-0366", email: "arizona@curaleaf.com", address: "1921 W Camelback Rd", city: "Phoenix", state: "AZ", zip: "85015", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO", "adult-use", "medical"], notes: "Multi-state operator. Multiple AZ locations." },
  { name: "Curaleaf Midtown", businessName: "Curaleaf Holdings Inc.", phone: "(602) 466-1087", email: "midtown@curaleaf.com", address: "1146 E McDowell Rd", city: "Phoenix", state: "AZ", zip: "85006", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO", "adult-use"] },
  { name: "Curaleaf Gilbert", businessName: "Curaleaf Holdings Inc.", phone: "(480) 500-3334", email: "gilbert@curaleaf.com", address: "1352 S Gilbert Rd Ste 111", city: "Gilbert", state: "AZ", zip: "85296", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO"] },
  { name: "Trulieve Phoenix", businessName: "Trulieve Cannabis Corp.", phone: "(602) 688-7980", email: "phoenix@trulieve.com", address: "1732 W Camelback Rd", city: "Phoenix", state: "AZ", zip: "85015", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO", "adult-use", "medical"], notes: "Major MSO, absorbed Harvest Health & Recreation." },
  { name: "Trulieve Glendale", businessName: "Trulieve Cannabis Corp.", phone: "(623) 565-3710", email: "glendale@trulieve.com", address: "5039 W Olive Ave", city: "Glendale", state: "AZ", zip: "85302", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO"] },
  { name: "Trulieve Casa Grande", businessName: "Trulieve Cannabis Corp.", phone: "(520) 233-4340", email: "casagrande@trulieve.com", address: "1640 E Florence Blvd", city: "Casa Grande", state: "AZ", zip: "85122", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO"] },
  { name: "Harvest HOC Scottsdale", businessName: "Harvest Health & Recreation", phone: "(480) 948-3737", email: "scottsdale@harvestinc.com", address: "15190 N Hayden Rd", city: "Scottsdale", state: "AZ", zip: "85260", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO", "Trulieve-subsidiary"] },
  { name: "Sol Flower Sun City", businessName: "Sol Flower LLC", phone: "(623) 236-6133", email: "suncity@solflower.com", address: "10540 W Bell Rd", city: "Sun City", state: "AZ", zip: "85351", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local", "adult-use", "medical"] },
  { name: "Sol Flower Tempe", businessName: "Sol Flower LLC", phone: "(480) 795-6363", email: "tempe@solflower.com", address: "1322 W Auto Dr Ste 107", city: "Tempe", state: "AZ", zip: "85284", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Sol Flower Scottsdale", businessName: "Sol Flower LLC", phone: "(480) 420-3020", email: "scottsdale@solflower.com", address: "8300 E Indian School Rd", city: "Scottsdale", state: "AZ", zip: "85251", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "The Mint Cannabis", businessName: "Mint Dispensary LLC", phone: "(623) 440-7600", email: "info@themintcannabis.com", address: "5210 S Power Rd", city: "Mesa", state: "AZ", zip: "85212", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local", "premium"], notes: "Known for The Mint Cafe concept." },
  { name: "Mint Cannabis Tempe", businessName: "Mint Dispensary LLC", phone: "(480) 749-6468", email: "tempe@themintcannabis.com", address: "1514 E Curry Rd", city: "Tempe", state: "AZ", zip: "85281", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Zen Leaf Phoenix", businessName: "Verano Holdings", phone: "(602) 254-2580", email: "phoenix@zenleaf.com", address: "4301 E McDowell Rd", city: "Phoenix", state: "AZ", zip: "85008", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO", "adult-use"] },
  { name: "Zen Leaf Mesa", businessName: "Verano Holdings", phone: "(480) 500-7219", email: "mesa@zenleaf.com", address: "945 E Main St", city: "Mesa", state: "AZ", zip: "85203", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO"] },
  { name: "Nirvana Center Apache Junction", businessName: "Nirvana Center LLC", phone: "(480) 671-1373", email: "aj@nirvanacenter.com", address: "10870 E Apache Trail", city: "Apache Junction", state: "AZ", zip: "85120", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Nirvana Center Phoenix", businessName: "Nirvana Center LLC", phone: "(602) 730-7573", email: "phoenix@nirvanacenter.com", address: "2 W Camelback Rd #101", city: "Phoenix", state: "AZ", zip: "85013", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Nirvana Center Tempe", businessName: "Nirvana Center LLC", phone: "(480) 378-6917", email: "tempe@nirvanacenter.com", address: "610 S Mill Ave", city: "Tempe", state: "AZ", zip: "85281", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Ayr Wellness Mesa", businessName: "Ayr Wellness Inc.", phone: "(480) 924-5577", email: "mesa@ayrwellness.com", address: "1502 E University Dr", city: "Mesa", state: "AZ", zip: "85203", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO"] },
  { name: "Ayr Wellness Scottsdale", businessName: "Ayr Wellness Inc.", phone: "(480) 386-2752", email: "scottsdale@ayrwellness.com", address: "15601 N 28th Ave", city: "Phoenix", state: "AZ", zip: "85053", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO"] },
  { name: "The Flower Shop", businessName: "Flower Shop AZ LLC", phone: "(480) 999-4748", email: "info@theflowershopaz.com", address: "940 W Broadway Rd", city: "Mesa", state: "AZ", zip: "85210", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local", "boutique"] },
  { name: "Territory Dispensary", businessName: "Territory Cannabis LLC", phone: "(480) 378-6908", email: "info@territorydispensary.com", address: "7200 E Camelback Rd", city: "Scottsdale", state: "AZ", zip: "85251", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local", "premium"] },
  { name: "Oasis Cannabis South Chandler", businessName: "Oasis Cannabis LLC", phone: "(480) 626-7333", email: "chandler@oasisdisp.com", address: "1721 S Arizona Ave", city: "Chandler", state: "AZ", zip: "85286", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Ponderosa Releaf", businessName: "Ponderosa Releaf LLC", phone: "(480) 771-4440", email: "info@ponderosareleaf.com", address: "9402 W Hatcher Rd", city: "Peoria", state: "AZ", zip: "85345", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Debbie's Dispensary", businessName: "Debbie's Dispensary LLC", phone: "(623) 738-4320", email: "info@debbiesdispensary.com", address: "20224 N 27th Ave", city: "Phoenix", state: "AZ", zip: "85027", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local", "value"] },
  { name: "Jars Cannabis Mesa", businessName: "JARS Holdings LLC", phone: "(480) 757-5090", email: "mesa@jarscannabis.com", address: "1850 S Country Club Dr", city: "Mesa", state: "AZ", zip: "85210", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "chain"] },
  { name: "Jars Cannabis Phoenix", businessName: "JARS Holdings LLC", phone: "(602) 354-3094", email: "phoenix@jarscannabis.com", address: "2040 W Northern Ave", city: "Phoenix", state: "AZ", zip: "85021", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "chain"] },
  { name: "Nature's Medicines Phoenix", businessName: "Nature's AZ Medicines LLC", phone: "(480) 420-3100", email: "info@naturesmedicines.com", address: "2439 W McDowell Rd", city: "Phoenix", state: "AZ", zip: "85009", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local"] },
  { name: "Sticky Saguaro", businessName: "Sticky Saguaro LLC", phone: "(520) 252-0202", email: "info@stickysaguaro.com", address: "1760 W Valencia Rd Ste 100", city: "Tucson", state: "AZ", zip: "85746", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "Tucson", "local"] },
  { name: "Prime Leaf Tucson", businessName: "Prime Leaf Inc.", phone: "(520) 447-7463", email: "info@primeleaf.com", address: "4220 E Speedway Blvd", city: "Tucson", state: "AZ", zip: "85712", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "Tucson", "local"] },
  { name: "D2 Dispensary Tucson", businessName: "D2 LLC", phone: "(520) 398-4494", email: "info@d2dispensary.com", address: "5720 E Broadway Blvd", city: "Tucson", state: "AZ", zip: "85711", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "Tucson"] },
  { name: "Harvest HOC Tucson", businessName: "Harvest Health & Recreation", phone: "(520) 468-4487", email: "tucson@harvestinc.com", address: "1040 W Ajo Way", city: "Tucson", state: "AZ", zip: "85713", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "MSO", "Tucson"] },
  { name: "Green Halo", businessName: "Green Halo LLC", phone: "(520) 308-6885", email: "info@greenhalo.org", address: "7831 N Oracle Rd", city: "Tucson", state: "AZ", zip: "85704", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "Tucson", "local"] },
  { name: "Earth's Healing South", businessName: "Earth's Healing LLC", phone: "(520) 395-1432", email: "info@earthshealing.com", address: "78 W River Rd", city: "Tucson", state: "AZ", zip: "85704", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "Tucson", "premium"] },
  { name: "Hana Meds Kingman", businessName: "Hana Meds Inc.", phone: "(928) 757-4750", email: "info@hanameds.com", address: "1713 Sycamore Ave", city: "Kingman", state: "AZ", zip: "86401", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "rural", "local"] },
  { name: "Giving Tree Dispensary", businessName: "Giving Tree Wellness Center LLC", phone: "(602) 777-7000", email: "info@givingtreeaz.com", address: "701 W Union Hills Dr #7", city: "Phoenix", state: "AZ", zip: "85027", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "local", "premium"] },
  { name: "Level Up Scottsdale", businessName: "Level Up LLC", phone: "(480) 664-2017", email: "info@levelupaz.com", address: "8535 E Hartford Dr", city: "Scottsdale", state: "AZ", zip: "85255", contactType: "dispensary", source: "scraper_import", licenseType: "Dispensary", jurisdiction: "AZ", tags: ["dispensary", "premium", "Scottsdale"] },
  // ═══════════════════ CULTIVATORS / GROWERS ═══════════════════
  { name: "Copperstate Farms", businessName: "Copperstate Farms LLC", phone: "(928) 474-0403", email: "info@copperstatefarms.com", address: "1702 AZ-260", city: "Snowflake", state: "AZ", zip: "85937", contactType: "grower", source: "scraper_import", licenseType: "Cultivator", jurisdiction: "AZ", tags: ["cultivator", "large-scale", "greenhouse"], notes: "One of the largest greenhouse cannabis farms in the US." },
  { name: "Aeriz Arizona", businessName: "Aeriz LLC", phone: "(602) 635-1800", email: "info@aeriz.com", address: "Phoenix, AZ", city: "Phoenix", state: "AZ", zip: "85009", contactType: "grower", source: "scraper_import", licenseType: "Cultivator", jurisdiction: "AZ", tags: ["cultivator", "aeroponic", "premium-flower"] },
  { name: "Abundant Organics", businessName: "Abundant Organics LLC", phone: "(480) 500-7000", email: "info@abundantorganics.com", address: "Phoenix, AZ", city: "Phoenix", state: "AZ", zip: "85043", contactType: "grower", source: "scraper_import", licenseType: "Cultivator", jurisdiction: "AZ", tags: ["cultivator", "organic", "craft"] },
  { name: "Grow Sciences", businessName: "Grow Sciences LLC", phone: "(480) 553-5555", email: "info@growsciences.com", address: "Tempe, AZ", city: "Tempe", state: "AZ", zip: "85281", contactType: "grower", source: "scraper_import", licenseType: "Cultivator", jurisdiction: "AZ", tags: ["cultivator", "concentrates", "premium"] },
  { name: "Sonoran Roots", businessName: "Sonoran Roots LLC", phone: "(623) 476-2050", email: "info@sonoranroots.com", address: "Phoenix, AZ", city: "Phoenix", state: "AZ", zip: "85043", contactType: "grower", source: "scraper_import", licenseType: "Cultivator", jurisdiction: "AZ", tags: ["cultivator", "craft", "small-batch"] },
  { name: "Tru Infusion", businessName: "Tru Infusion LLC", phone: "(602) 900-4200", email: "info@truinfusion.com", address: "Phoenix, AZ", city: "Phoenix", state: "AZ", zip: "85043", contactType: "processor", source: "scraper_import", licenseType: "Processor/Cultivator", jurisdiction: "AZ", tags: ["processor", "edibles", "infused-products"] },
  { name: "Item 9 Labs", businessName: "Item 9 Labs Corp.", phone: "(480) 385-2791", email: "info@item9labs.com", address: "Coolidge, AZ", city: "Coolidge", state: "AZ", zip: "85128", contactType: "grower", source: "scraper_import", licenseType: "Cultivator", jurisdiction: "AZ", tags: ["cultivator", "vapes", "concentrates", "publicly-traded"] },
  // ═══════════════════ PHYSICIANS / CERTIFIERS ═══════════════════
  { name: "Dr. Reeferalz", businessName: "AZ Medical Marijuana Certifications", phone: "(480) 571-1950", email: "info@drreeferalz.com", address: "7135 E Camelback Rd #230", city: "Scottsdale", state: "AZ", zip: "85251", contactType: "provider", source: "scraper_import", licenseType: "Physician/Certifier", jurisdiction: "AZ", tags: ["physician", "medical-card", "certifier"] },
  { name: "NuggMD Arizona", businessName: "NuggMD Inc.", phone: "(844) 484-3288", email: "support@nuggmd.com", address: "Telehealth - Arizona", city: "Phoenix", state: "AZ", zip: "85001", contactType: "provider", source: "scraper_import", licenseType: "Telehealth Certifier", jurisdiction: "AZ", tags: ["physician", "telehealth", "medical-card"], notes: "Telehealth platform for AZ medical card certifications." },
  { name: "Leafwell Arizona", businessName: "Leafwell Botanicals Inc.", phone: "(800) 660-9085", email: "support@leafwell.com", address: "Telehealth - Arizona", city: "Phoenix", state: "AZ", zip: "85001", contactType: "provider", source: "scraper_import", licenseType: "Telehealth Certifier", jurisdiction: "AZ", tags: ["physician", "telehealth", "medical-card"] },
  // ═══════════════════ ATTORNEYS ═══════════════════
  { name: "Thomas Dean & Hoskins", businessName: "Thomas Dean & Hoskins PLC", phone: "(602) 257-0800", email: "info@tdhlaw.com", address: "2701 E Camelback Rd #140", city: "Phoenix", state: "AZ", zip: "85016", contactType: "attorney", source: "scraper_import", licenseType: "Law Firm", jurisdiction: "AZ", tags: ["attorney", "cannabis-law", "licensing"], notes: "Cannabis licensing & compliance firm." },
  { name: "Beus Gilbert McGroder", businessName: "Beus Gilbert McGroder PLLC", phone: "(480) 429-3000", email: "info@beusgilbert.com", address: "701 N 44th St Ste 400", city: "Phoenix", state: "AZ", zip: "85008", contactType: "attorney", source: "scraper_import", licenseType: "Law Firm", jurisdiction: "AZ", tags: ["attorney", "litigation", "cannabis-law"] },
  { name: "Snell & Wilmer Cannabis", businessName: "Snell & Wilmer LLP", phone: "(602) 382-6000", email: "info@swlaw.com", address: "400 E Van Buren St", city: "Phoenix", state: "AZ", zip: "85004", contactType: "attorney", source: "scraper_import", licenseType: "Law Firm", jurisdiction: "AZ", tags: ["attorney", "corporate", "cannabis-regulatory"] },
  // ═══════════════════ GOVERNMENT / REGULATORY ═══════════════════
  { name: "AZ Dept of Health Services", businessName: "ADHS - Medical Marijuana Program", phone: "(602) 542-1025", email: "medicalmarijuana@azdhs.gov", address: "150 N 18th Ave Ste 460", city: "Phoenix", state: "AZ", zip: "85007", contactType: "regulator", source: "gov_advocate_import", licenseType: "State Regulator", jurisdiction: "AZ", tags: ["government", "regulator", "ADHS", "licensing-authority"], notes: "Primary regulatory body for AZ medical marijuana." },
  { name: "AZ Dept of Revenue - Marijuana", businessName: "ADOR Marijuana Tax Unit", phone: "(602) 255-3381", email: "taxpayerassistance@azdor.gov", address: "1600 W Monroe St", city: "Phoenix", state: "AZ", zip: "85007", contactType: "regulator", source: "gov_advocate_import", licenseType: "Tax Authority", jurisdiction: "AZ", tags: ["government", "tax", "revenue", "excise-tax"] },
];

export default AZ_LEADS;
