import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export async function generateOmmaPdf(formType: string, data: any, submissionId: string) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // US Letter
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = 750;

  // Header
  page.drawText('OKLAHOMA MEDICAL MARIJUANA AUTHORITY', {
    x: 50,
    y,
    size: 18,
    font: boldFont,
    color: rgb(0.05, 0.4, 0.1),
  });
  y -= 30;

  page.drawText(formType.replace(/([A-Z])/g, ' $1').trim(), {
    x: 50,
    y,
    size: 22,
    font: boldFont,
  });
  y -= 40;

  // Form Data
  page.drawText(`Submission ID: ${submissionId}`, { x: 50, y, size: 12, font });
  y -= 25;

  Object.entries(data).forEach(([key, value]) => {
    if (typeof value === 'string' && value) {
      page.drawText(`${key.replace(/([A-Z])/g, ' $1')}: ${value}`, {
        x: 50,
        y,
        size: 11,
        font,
      });
      y -= 18;
      if (y < 50) {
        pdfDoc.addPage([612, 792]);
        y = 750;
      }
    }
  });

  // Footer
  page.drawText('Official OMMA Form • Generated by SINC Compliance Engine', {
    x: 50,
    y: 40,
    size: 9,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}
