// ============================================================
// GGMA National Enforcement Tracker — State Source Configuration
// Each entry maps a state to its OFFICIAL enforcement/disciplinary
// actions page (NOT the license directory — that's different).
// ============================================================

export const STATE_ENFORCEMENT_SOURCES = {
  OK: {
    name: 'Oklahoma',
    authority: 'Oklahoma Medical Marijuana Authority (OMMA)',
    enforcementUrl: 'https://oklahoma.gov/omma/compliance-and-enforcement.html',
    licenseSearchUrl: 'https://medportal.omma.ok.gov/s/verify-license-number',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'OMMA does NOT maintain compiled enforcement records per FOIA response. We scrape license status changes from their public portal.',
  },
  CA: {
    name: 'California',
    authority: 'Department of Cannabis Control (DCC)',
    enforcementUrl: 'https://cannabis.ca.gov/cannabis-laws/compliance-with-state-law/',
    licenseSearchUrl: 'https://search.cannabis.ca.gov/',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'DCC publishes enforcement actions including citations, fines, and license suspensions.',
  },
  CO: {
    name: 'Colorado',
    authority: 'Marijuana Enforcement Division (MED)',
    enforcementUrl: 'https://sbg.colorado.gov/med-disciplinary-actions',
    licenseSearchUrl: 'https://sbg.colorado.gov/med',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'MED publishes disciplinary actions in tabular format.',
  },
  OR: {
    name: 'Oregon',
    authority: 'Oregon Liquor & Cannabis Commission (OLCC)',
    enforcementUrl: 'https://www.oregon.gov/olcc/marijuana/Pages/Compliance.aspx',
    licenseSearchUrl: 'https://www.oregon.gov/olcc/marijuana/Pages/Licensees.aspx',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'OLCC lists compliance actions and final orders.',
  },
  WA: {
    name: 'Washington',
    authority: 'Liquor and Cannabis Board (LCB)',
    enforcementUrl: 'https://lcb.wa.gov/enforcement/enforcement-actions',
    licenseSearchUrl: 'https://lcb.wa.gov/',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'LCB publishes enforcement actions for cannabis licensees.',
  },
  MI: {
    name: 'Michigan',
    authority: 'Cannabis Regulatory Agency (CRA)',
    enforcementUrl: 'https://www.michigan.gov/cra/about/enforcement',
    licenseSearchUrl: 'https://aca-prod.accela.com/MIMM/Default.aspx',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'CRA publishes enforcement summaries and consent orders.',
  },
  IL: {
    name: 'Illinois',
    authority: 'Illinois Dept of Financial & Professional Regulation (IDFPR)',
    enforcementUrl: 'https://idfpr.illinois.gov/profs/adultusecan.asp',
    licenseSearchUrl: 'https://online-dfpr.micropact.com/lookup/licenselookup.aspx',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'IDFPR publishes disciplinary reports on adult-use cannabis licensees.',
  },
  FL: {
    name: 'Florida',
    authority: 'Office of Medical Marijuana Use (OMMU)',
    enforcementUrl: 'https://knowthefactsmmj.com/about/actions/',
    licenseSearchUrl: 'https://knowthefactsmmj.com/',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'OMMU posts enforcement actions on the Know the Facts site.',
  },
  MO: {
    name: 'Missouri',
    authority: 'Division of Cannabis Regulation (DCR)',
    enforcementUrl: 'https://health.mo.gov/safety/medical-marijuana/enforcement.php',
    licenseSearchUrl: 'https://mo-public.mycomplia.com/login',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'Missouri DCR publishes enforcement actions and violations.',
  },
  MD: {
    name: 'Maryland',
    authority: 'Maryland Cannabis Administration (MCA)',
    enforcementUrl: 'https://cannabis.maryland.gov/Pages/enforcement.aspx',
    licenseSearchUrl: 'https://cannabis.maryland.gov/Pages/Industry_Licensees_and_Registrants.aspx',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'MCA publishes enforcement actions and sanctions.',
  },
  NV: {
    name: 'Nevada',
    authority: 'Cannabis Compliance Board (CCB)',
    enforcementUrl: 'https://ccb.nv.gov/enforcement-actions/',
    licenseSearchUrl: 'https://ccb.nv.gov/',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'CCB publishes enforcement actions and board orders.',
  },
  AZ: {
    name: 'Arizona',
    authority: 'Dept of Health Services (ADHS)',
    enforcementUrl: 'https://www.azdhs.gov/licensing/medical-marijuana/',
    licenseSearchUrl: 'https://individual-licensing.azdhs.gov/s/login/',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'ADHS publishes compliance and enforcement information.',
  },
  MA: {
    name: 'Massachusetts',
    authority: 'Cannabis Control Commission (CCC)',
    enforcementUrl: 'https://masscannabiscontrol.com/actions-and-orders/',
    licenseSearchUrl: 'https://masscannabiscontrol.com/',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'CCC publishes enforcement actions and final orders.',
  },
  NJ: {
    name: 'New Jersey',
    authority: 'Cannabis Regulatory Commission (CRC)',
    enforcementUrl: 'https://www.nj.gov/cannabis/enforcement/',
    licenseSearchUrl: 'https://www.nj.gov/cannabis/businesses/',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'NJ CRC publishes enforcement and compliance actions.',
  },
  OH: {
    name: 'Ohio',
    authority: 'Division of Cannabis Control (DCC)',
    enforcementUrl: 'https://com.ohio.gov/divisions-and-programs/cannabis-control',
    licenseSearchUrl: 'https://com.ohio.gov/divisions-and-programs/cannabis-control',
    format: 'html_table',
    strategy: 'puppeteer',
    notes: 'Ohio DCC publishes disciplinary actions and final orders.',
  },
  NY: {
    name: 'New York',
    authority: 'Office of Cannabis Management (OCM)',
    enforcementUrl: 'https://cannabis.ny.gov/enforcement',
    licenseSearchUrl: 'https://cannabis.ny.gov/licensing',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'NY OCM publishes enforcement actions and license revocations.',
  },
  PA: {
    name: 'Pennsylvania',
    authority: 'Dept of Health Medical Marijuana Program',
    enforcementUrl: 'https://www.health.pa.gov/topics/programs/Medical%20Marijuana/',
    licenseSearchUrl: 'https://www.health.pa.gov/topics/programs/Medical%20Marijuana/',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'PA DOH publishes compliance summaries for medical marijuana.',
  },
  MS: {
    name: 'Mississippi',
    authority: 'Mississippi Medical Cannabis Program (MMCP)',
    enforcementUrl: 'https://www.mmcp.ms.gov/compliance',
    licenseSearchUrl: 'https://www.mmcp.ms.gov/businesses',
    format: 'html_list',
    strategy: 'puppeteer',
    notes: 'MMCP publishes compliance and enforcement actions.',
  },
};

// Confidence tiers for display
export const CONFIDENCE_TIERS = {
  VERIFIED: { label: 'Verified', maxAgeDays: 7, color: 'green', publicVisible: true },
  STALE: { label: 'Stale', maxAgeDays: 30, color: 'yellow', publicVisible: true },
  UNVERIFIED: { label: 'Unverified', maxAgeDays: Infinity, color: 'red', publicVisible: false },
};

// Normalized enforcement action types
export const ACTION_TYPES = [
  'Suspension',
  'Revocation',
  'Forfeiture',
  'Surrender',
  'Fine',
  'Warning',
  'Citation',
  'Consent Order',
  'Emergency Suspension',
  'Probation',
  'Reinstatement',
];
