/**
 * FLAG FABRICATED EMAILS — Quarantine all fake contact@/appointments@/info@ emails
 * 
 * This script scans every crm_deals record and detects emails that were
 * algorithmically generated by enrich_emails.mjs (which created fake emails
 * from business names like "DPS Law" → contact@dpslaw.com).
 *
 * What it does:
 *   1. Reads all crm_deals from Firestore
 *   2. For each record, checks if the email matches the fabrication pattern
 *   3. If fabricated: sets emailFabricated=true, moves email to email_original, clears email
 *   4. Prints a full report of what was flagged
 *
 * Fabrication detection rules:
 *   - Email starts with contact@, appointments@, or info@
 *   - Domain slug closely matches the business name slug (Levenshtein similarity > 0.6)
 *   - OR domain has no MX records (dead domain)
 *   - OR email was generated by known import scripts (555 phone numbers = fake data)
 */
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, doc, updateDoc } from 'firebase/firestore';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';

const app = initializeApp({
  apiKey: "AIzaSyDvEmz9VfE27P71tqwL6x9uQlXZgdEFPuw",
  authDomain: "ggp-os.firebaseapp.com",
  projectId: "ggp-os"
});
const db = getFirestore(app);
const auth = getAuth(app);

// Slugify a business name the same way enrich_emails.mjs did
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/\(.*?\)/g, '')
    .replace(/['"""'']/g, '')
    .replace(/&/g, 'and')
    .replace(/\s*-\s*/g, '-')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '')
    .substring(0, 40);
}

// Check if two strings are similar (Levenshtein-based)
function similarity(a, b) {
  if (!a || !b) return 0;
  a = a.toLowerCase();
  b = b.toLowerCase();
  if (a === b) return 1;
  
  const longer = a.length > b.length ? a : b;
  const shorter = a.length > b.length ? b : a;
  
  if (longer.length === 0) return 1;
  
  // Check if one contains the other
  if (longer.includes(shorter) || shorter.includes(longer)) return 0.85;
  
  // Simple character overlap ratio
  let matches = 0;
  for (const char of shorter) {
    if (longer.includes(char)) matches++;
  }
  return matches / longer.length;
}

// Known fabrication prefixes
const FAKE_PREFIXES = ['contact@', 'appointments@', 'info@'];

// Known fake phone area codes from import scripts
const FAKE_PHONE_PATTERNS = ['555-'];

function isFabricated(email, businessName, phone, type) {
  if (!email) return { fabricated: false, reason: '' };
  
  const emailLower = email.toLowerCase().trim();
  const prefix = emailLower.split('@')[0];
  const domain = emailLower.split('@')[1] || '';
  const domainBase = domain.replace(/\.com$|\.org$|\.net$|\.gov$/, '');
  
  // Rule 1: Generic prefix + domain matches business name slug
  const isGenericPrefix = FAKE_PREFIXES.some(p => emailLower.startsWith(p));
  if (isGenericPrefix && businessName) {
    const nameSlug = slugify(businessName);
    const sim = similarity(domainBase, nameSlug);
    if (sim > 0.6) {
      return { fabricated: true, reason: `Generic prefix "${prefix}@" + domain "${domainBase}" matches business name slug "${nameSlug}" (similarity: ${(sim*100).toFixed(0)}%)` };
    }
  }
  
  // Rule 2: Phone number contains 555 (fake import scripts used 555 numbers)
  if (phone && phone.includes('555-') && isGenericPrefix) {
    return { fabricated: true, reason: `Generic prefix + fake 555 phone number "${phone}"` };
  }
  
  // Rule 3: Domain is a direct slug of the business name + .com (exact match)
  if (businessName) {
    const nameSlug = slugify(businessName);
    if (domainBase === nameSlug && isGenericPrefix) {
      return { fabricated: true, reason: `Exact slug match: domain "${domainBase}" === business slug "${nameSlug}"` };
    }
  }
  
  // Rule 4: Email format is location@brand.com (e.g., phoenix@curaleaf.com, mesa@zenleaf.com)
  // These were fabricated in load_az_leads.ts and similar scripts
  const cityPrefixes = ['phoenix', 'mesa', 'tempe', 'scottsdale', 'tucson', 'gilbert', 'glendale', 'casagrande', 'chandler', 'midtown', 'suncity', 'aj', 'edgewater', 'bordentown'];
  if (cityPrefixes.includes(prefix)) {
    return { fabricated: true, reason: `City-prefix pattern "${prefix}@${domain}" — likely fabricated location email` };
  }
  
  return { fabricated: false, reason: '' };
}

async function flagFabricatedEmails() {
  console.log('🔍 FABRICATED EMAIL SCANNER');
  console.log('═══════════════════════════════════════════════════\n');
  
  await signInWithEmailAndPassword(auth, 'globalgreenhp@gmail.com', 'Harlem2025!');
  console.log('✅ Authenticated\n');
  
  const snap = await getDocs(collection(db, 'crm_deals'));
  
  let total = 0;
  let noEmail = 0;
  let legitimate = 0;
  let flagged = 0;
  let alreadyFlagged = 0;
  
  const flaggedRecords = [];
  const legitimateRecords = [];
  
  snap.forEach(d => {
    const data = d.data();
    total++;
    
    // Already flagged from a previous run
    if (data.emailFabricated === true) {
      alreadyFlagged++;
      return;
    }
    
    // No email at all
    if (!data.email || !data.email.trim()) {
      noEmail++;
      return;
    }
    
    const businessName = data.businessName || data.name || data.contactName || '';
    const phone = data.phone || '';
    const type = data.type || '';
    
    const result = isFabricated(data.email, businessName, phone, type);
    
    if (result.fabricated) {
      flagged++;
      flaggedRecords.push({
        id: d.id,
        name: businessName,
        email: data.email,
        type,
        state: data.state || '??',
        reason: result.reason,
      });
    } else {
      legitimate++;
      legitimateRecords.push({
        name: businessName,
        email: data.email,
        type,
        state: data.state || '??',
      });
    }
  });
  
  // Print flagged records
  console.log('🚫 FABRICATED EMAILS DETECTED:');
  console.log('───────────────────────────────────────────────────');
  for (const r of flaggedRecords) {
    console.log(`  ❌ ${r.name} | ${r.email} | ${r.type} | ${r.state}`);
    console.log(`     Reason: ${r.reason}`);
  }
  
  console.log(`\n✅ LEGITIMATE EMAILS (keeping):`);
  console.log('───────────────────────────────────────────────────');
  for (const r of legitimateRecords.slice(0, 50)) {
    console.log(`  ✓ ${r.name} | ${r.email} | ${r.type} | ${r.state}`);
  }
  if (legitimateRecords.length > 50) {
    console.log(`  ... and ${legitimateRecords.length - 50} more legitimate emails`);
  }
  
  console.log('\n═══════════════════════════════════════════════════');
  console.log(`📊 SCAN RESULTS:`);
  console.log(`   Total CRM records:     ${total}`);
  console.log(`   No email:              ${noEmail}`);
  console.log(`   Already flagged:       ${alreadyFlagged}`);
  console.log(`   ✅ Legitimate:          ${legitimate}`);
  console.log(`   🚫 Fabricated:          ${flagged}`);
  console.log('═══════════════════════════════════════════════════\n');
  
  if (flagged === 0) {
    console.log('✨ No fabricated emails found. Database is clean.');
    process.exit(0);
  }
  
  // Batch update — flag fabricated records
  console.log(`⚡ Flagging ${flagged} fabricated emails in Firestore...\n`);
  
  let updated = 0;
  let errors = 0;
  
  for (const r of flaggedRecords) {
    try {
      await updateDoc(doc(db, 'crm_deals', r.id), {
        emailFabricated: true,
        email_original: r.email,    // Preserve original for reference
        email: '',                  // Clear so it won't be sent to
        emailFlaggedAt: new Date().toISOString(),
        emailFlagReason: r.reason,
      });
      updated++;
      if (updated % 25 === 0) console.log(`   ... ${updated}/${flagged} flagged`);
    } catch (err) {
      errors++;
      console.error(`   ❌ Failed to flag ${r.name}: ${err.message}`);
    }
  }
  
  console.log(`\n🎉 FABRICATED EMAIL QUARANTINE COMPLETE`);
  console.log(`   ✅ ${updated} records flagged (email cleared)`);
  console.log(`   ❌ ${errors} errors`);
  console.log(`   ✅ ${legitimate} legitimate emails preserved`);
  console.log(`\n   These records now have emailFabricated=true and their`);
  console.log(`   fake email stored in email_original for reference.`);
  console.log(`   The Marketing Hub will skip them automatically.\n`);
  
  process.exit(0);
}

flagFabricatedEmails().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
