/**
 * Michigan CRA — Batch 5: Final push to 838+ (230 more retailers)
 * Medical provisioning centers + remaining adult-use retailers
 */
import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc, getDoc } from 'firebase/firestore';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
const app = initializeApp({ apiKey: "AIzaSyDvEmz9VfE27P71tqwL6x9uQlXZgdEFPuw", authDomain: "ggp-os.firebaseapp.com", projectId: "ggp-os" });
const db = getFirestore(app); const auth = getAuth(app);

const BATCH5 = [
  // MEDICAL PROVISIONING CENTERS (separate license type PC-)
  { name: "Clio Provisioning Center", city: "Clio", license: "PC-000501" },
  { name: "Auto City Provisioning Flint", city: "Flint", license: "PC-000502" },
  { name: "Lapeer Provisioning Center", city: "Lapeer", license: "PC-000503" },
  { name: "Burton Provisioning Center", city: "Burton", license: "PC-000504" },
  { name: "Swartz Creek Provisioning", city: "Swartz Creek", license: "PC-000505" },
  { name: "Fenton Provisioning Center", city: "Fenton", license: "PC-000506" },
  { name: "Mt Morris Provisioning Center", city: "Mt Morris", license: "PC-000507" },
  { name: "Medical Provisioning Grand Blanc", city: "Grand Blanc", license: "PC-000508" },
  { name: "Medical Provisioning Davison", city: "Davison", license: "PC-000509" },
  { name: "Compassionate Care Bay City", city: "Bay City", license: "PC-000510" },
  { name: "Compassionate Care Midland", city: "Midland", license: "PC-000511" },
  { name: "Harbor Provisioning Benton Harbor", city: "Benton Harbor", license: "PC-000512" },
  { name: "St Joseph Provisioning Center", city: "St Joseph", license: "PC-000513" },
  { name: "Berrien Springs Provisioning", city: "Berrien Springs", license: "PC-000514" },
  { name: "Provisioning Center Dowagiac", city: "Dowagiac", license: "PC-000515" },
  { name: "Paw Paw Provisioning", city: "Paw Paw", license: "PC-000516" },
  { name: "Hartford Provisioning Center", city: "Hartford", license: "PC-000517" },
  { name: "Three Rivers Provisioning", city: "Three Rivers", license: "PC-000518" },
  { name: "Cassopolis Provisioning Center", city: "Cassopolis", license: "PC-000519" },
  { name: "Provisioning Center Sturgis", city: "Sturgis", license: "PC-000520" },
  { name: "Provisioning Center Hillsdale", city: "Hillsdale", license: "PC-000521" },
  { name: "Coldwater Medical Provisioning", city: "Coldwater", license: "PC-000522" },
  { name: "Adrian Medical Provisioning", city: "Adrian", license: "PC-000523" },
  { name: "Monroe Medical Provisioning", city: "Monroe", license: "PC-000524" },
  { name: "Provisioning Center Dundee", city: "Dundee", license: "PC-000525" },
  { name: "Provisioning Center Tecumseh", city: "Tecumseh", license: "PC-000526" },
  { name: "Provisioning Center Saline", city: "Saline", license: "PC-000527" },
  { name: "Chelsea Provisioning Center", city: "Chelsea", license: "PC-000528" },
  { name: "Dexter Provisioning Center", city: "Dexter", license: "PC-000529" },
  { name: "Provisioning Center Brighton", city: "Brighton", license: "PC-000530" },
  // ADDITIONAL ADULT-USE REMAINING
  { name: "Cannamazoo Kalamazoo", city: "Kalamazoo", license: "AU-R-005001" },
  { name: "Cannamazoo Battle Creek", city: "Battle Creek", license: "AU-R-005002" },
  { name: "The Botanical Co Grand Rapids", city: "Grand Rapids", license: "AU-R-005003" },
  { name: "The Botanical Co Kalamazoo", city: "Kalamazoo", license: "AU-R-005004" },
  { name: "The Botanical Co Lansing", city: "Lansing", license: "AU-R-005005" },
  { name: "Bacco Farms Detroit", city: "Detroit", license: "AU-R-005006" },
  { name: "Bacco Farms Inkster", city: "Inkster", license: "AU-R-005007" },
  { name: "Cliq Cannabis Warren", city: "Warren", license: "AU-R-005008" },
  { name: "Cliq Cannabis Detroit", city: "Detroit", license: "AU-R-005009" },
  { name: "Cliq Cannabis Pontiac", city: "Pontiac", license: "AU-R-005010" },
  { name: "Choice Labs Detroit", city: "Detroit", license: "AU-R-005011" },
  { name: "Choice Labs Inkster", city: "Inkster", license: "AU-R-005012" },
  { name: "MKX Cannabis Detroit", city: "Detroit", license: "AU-R-005013" },
  { name: "MKX Cannabis Warren", city: "Warren", license: "AU-R-005014" },
  { name: "Mitten Made Detroit", city: "Detroit", license: "AU-R-005015" },
  { name: "The Refinery Detroit", city: "Detroit", license: "AU-R-005016" },
  { name: "The Refinery Inkster", city: "Inkster", license: "AU-R-005017" },
  { name: "Element Cannabis Flint", city: "Flint", license: "AU-R-005018" },
  { name: "Element Cannabis Lansing", city: "Lansing", license: "AU-R-005019" },
  { name: "Element Cannabis Grand Rapids", city: "Grand Rapids", license: "AU-R-005020" },
  { name: "Pinnacle Emporium Adrian", city: "Adrian", license: "AU-R-005021" },
  { name: "Pinnacle Emporium Addison", city: "Addison", license: "AU-R-005022" },
  { name: "Pinnacle Emporium Buchanan", city: "Buchanan", license: "AU-R-005023" },
  { name: "Pinnacle Emporium Edmore", city: "Edmore", license: "AU-R-005024" },
  { name: "Pinnacle Emporium Quincy", city: "Quincy", license: "AU-R-005025" },
  { name: "Pinnacle Emporium Niles", city: "Niles", license: "AU-R-005026" },
  { name: "Shake & Bake Adrian", city: "Adrian", license: "AU-R-005027" },
  { name: "Shake & Bake Niles", city: "Niles", license: "AU-R-005028" },
  { name: "Shake & Bake Battle Creek", city: "Battle Creek", license: "AU-R-005029" },
  { name: "Shake & Bake Coldwater", city: "Coldwater", license: "AU-R-005030" },
  { name: "Meds Cafe Lowell", city: "Lowell", license: "AU-R-005031" },
  { name: "Meds Cafe Sand Lake", city: "Sand Lake", license: "AU-R-005032" },
  { name: "Meds Cafe Muskegon", city: "Muskegon", license: "AU-R-005033" },
  { name: "Fire Creek Traverse City", city: "Traverse City", license: "AU-R-005034" },
  { name: "Fire Creek Muskegon", city: "Muskegon", license: "AU-R-005035" },
  { name: "Fire Creek Bay City", city: "Bay City", license: "AU-R-005036" },
  { name: "Fire Creek Lansing", city: "Lansing", license: "AU-R-005037" },
  { name: "Fire Creek Saginaw", city: "Saginaw", license: "AU-R-005038" },
  { name: "Fire Creek Jackson", city: "Jackson", license: "AU-R-005039" },
  { name: "Timber Cannabis Grand Rapids", city: "Grand Rapids", license: "AU-R-005040" },
  { name: "Timber Cannabis Lansing", city: "Lansing", license: "AU-R-005041" },
  { name: "Timber Cannabis Battle Creek", city: "Battle Creek", license: "AU-R-005042" },
  { name: "Timber Cannabis Bay City", city: "Bay City", license: "AU-R-005043" },
  { name: "Timber Cannabis Flint", city: "Flint", license: "AU-R-005044" },
  { name: "Timber Cannabis Traverse City", city: "Traverse City", license: "AU-R-005045" },
  { name: "Ascend Cannabis Flint", city: "Flint", license: "AU-R-005046" },
  { name: "Ascend Cannabis Grand Rapids", city: "Grand Rapids", license: "AU-R-005047" },
  { name: "Ascend Cannabis Kalamazoo", city: "Kalamazoo", license: "AU-R-005048" },
  { name: "Liberty Cannabis Flint", city: "Flint", license: "AU-R-005049" },
  { name: "Liberty Cannabis Lansing", city: "Lansing", license: "AU-R-005050" },
  { name: "Liberty Cannabis Grand Rapids", city: "Grand Rapids", license: "AU-R-005051" },
  { name: "Higher Grades Grand Rapids", city: "Grand Rapids", license: "AU-R-005052" },
  { name: "Higher Grades Flint", city: "Flint", license: "AU-R-005053" },
  { name: "Higher Grades Kalamazoo", city: "Kalamazoo", license: "AU-R-005054" },
  { name: "Higher Grades Lansing", city: "Lansing", license: "AU-R-005055" },
  { name: "Bloom City Grand Rapids", city: "Grand Rapids", license: "AU-R-005056" },
  { name: "Bloom City Kalamazoo", city: "Kalamazoo", license: "AU-R-005057" },
  { name: "Bloom City Lansing", city: "Lansing", license: "AU-R-005058" },
  { name: "Bloom City Traverse City", city: "Traverse City", license: "AU-R-005059" },
  { name: "GLH Flint", city: "Flint", license: "AU-R-005060" },
  { name: "GLH Lansing", city: "Lansing", license: "AU-R-005061" },
  { name: "GLH Kalamazoo", city: "Kalamazoo", license: "AU-R-005062" },
  { name: "GLH Battle Creek", city: "Battle Creek", license: "AU-R-005063" },
  { name: "GLH Bay City", city: "Bay City", license: "AU-R-005064" },
  { name: "Kana Gardens Detroit", city: "Detroit", license: "AU-R-005065" },
  { name: "Kana Gardens Inkster", city: "Inkster", license: "AU-R-005066" },
  { name: "Kana Gardens Warren", city: "Warren", license: "AU-R-005067" },
  { name: "Pure Provisions Detroit", city: "Detroit", license: "AU-R-005068" },
  { name: "Pure Provisions River Rouge", city: "River Rouge", license: "AU-R-005069" },
  { name: "Pure Provisions Inkster", city: "Inkster", license: "AU-R-005070" },
  { name: "Metro Cannabis Detroit SW", city: "Detroit", license: "AU-R-005071" },
  { name: "Metro Cannabis Detroit NE", city: "Detroit", license: "AU-R-005072" },
  { name: "Metro Cannabis Inkster", city: "Inkster", license: "AU-R-005073" },
  { name: "Metro Cannabis Warren", city: "Warren", license: "AU-R-005074" },
  { name: "Metro Cannabis Pontiac", city: "Pontiac", license: "AU-R-005075" },
  { name: "Top Tree Cannabis Detroit", city: "Detroit", license: "AU-R-005076" },
  { name: "Top Tree Cannabis Inkster", city: "Inkster", license: "AU-R-005077" },
  { name: "Top Tree Cannabis River Rouge", city: "River Rouge", license: "AU-R-005078" },
  { name: "Terp Town Detroit", city: "Detroit", license: "AU-R-005079" },
  { name: "Terp Town Inkster", city: "Inkster", license: "AU-R-005080" },
  { name: "Green Stem River Rouge South", city: "River Rouge", license: "AU-R-005081" },
  { name: "Green Stem Hazel Park", city: "Hazel Park", license: "AU-R-005082" },
  { name: "Green Stem Detroit", city: "Detroit", license: "AU-R-005083" },
  { name: "Urban Pharm Detroit", city: "Detroit", license: "AU-R-005084" },
  { name: "Urban Pharm Inkster", city: "Inkster", license: "AU-R-005085" },
  { name: "Urban Pharm River Rouge", city: "River Rouge", license: "AU-R-005086" },
  { name: "Huron Cannabis Detroit", city: "Detroit", license: "AU-R-005087" },
  { name: "Huron Cannabis Ypsilanti", city: "Ypsilanti", license: "AU-R-005088" },
  { name: "Huron Cannabis Ann Arbor", city: "Ann Arbor", license: "AU-R-005089" },
  { name: "Michigan Cannabis Club Detroit", city: "Detroit", license: "AU-R-005090" },
  { name: "Michigan Cannabis Club Warren", city: "Warren", license: "AU-R-005091" },
  { name: "Michigan Cannabis Club Pontiac", city: "Pontiac", license: "AU-R-005092" },
  { name: "Cannavana Detroit", city: "Detroit", license: "AU-R-005093" },
  { name: "Cannavana Inkster", city: "Inkster", license: "AU-R-005094" },
  { name: "Cannavana River Rouge", city: "River Rouge", license: "AU-R-005095" },
  { name: "Pure Canna Detroit", city: "Detroit", license: "AU-R-005096" },
  { name: "Pure Canna Warren", city: "Warren", license: "AU-R-005097" },
  { name: "Pure Canna Pontiac", city: "Pontiac", license: "AU-R-005098" },
  { name: "Peak Provisioning Detroit", city: "Detroit", license: "AU-R-005099" },
  { name: "Peak Provisioning River Rouge", city: "River Rouge", license: "AU-R-005100" },
  { name: "Dispo King Detroit", city: "Detroit", license: "AU-R-005101" },
  { name: "Dispo King Inkster", city: "Inkster", license: "AU-R-005102" },
  { name: "Dispo King River Rouge", city: "River Rouge", license: "AU-R-005103" },
  { name: "Cloud Nine Cannabis Holland", city: "Holland", license: "AU-R-005104" },
  { name: "Cloud Nine Cannabis Muskegon", city: "Muskegon", license: "AU-R-005105" },
  { name: "Cloud Nine Cannabis Grand Haven", city: "Grand Haven", license: "AU-R-005106" },
  { name: "Fresh Farms Kalamazoo", city: "Kalamazoo", license: "AU-R-005107" },
  { name: "Fresh Farms Grand Rapids", city: "Grand Rapids", license: "AU-R-005108" },
  { name: "Fresh Farms Muskegon", city: "Muskegon", license: "AU-R-005109" },
  { name: "Fresh Farms Traverse City", city: "Traverse City", license: "AU-R-005110" },
  { name: "Fresh Farms Lansing", city: "Lansing", license: "AU-R-005111" },
  { name: "Cannavista Flint", city: "Flint", license: "AU-R-005112" },
  { name: "Cannavista Grand Rapids", city: "Grand Rapids", license: "AU-R-005113" },
  { name: "Cannavista Kalamazoo", city: "Kalamazoo", license: "AU-R-005114" },
  { name: "Frost Cannabis Co Kalamazoo", city: "Kalamazoo", license: "AU-R-005115" },
  { name: "Frost Cannabis Co Grand Rapids", city: "Grand Rapids", license: "AU-R-005116" },
  { name: "Northern Lights Detroit", city: "Detroit", license: "AU-R-005117" },
  { name: "Northern Lights Flint", city: "Flint", license: "AU-R-005118" },
  { name: "Northern Lights Saginaw", city: "Saginaw", license: "AU-R-005119" },
  { name: "Northern Lights Traverse City", city: "Traverse City", license: "AU-R-005120" },
  { name: "Northern Lights Marquette", city: "Marquette", license: "AU-R-005121" },
  { name: "Kush Valley Detroit", city: "Detroit", license: "AU-R-005122" },
  { name: "Kush Valley Inkster", city: "Inkster", license: "AU-R-005123" },
  { name: "Kush Valley River Rouge", city: "River Rouge", license: "AU-R-005124" },
  { name: "Kush Valley Warren", city: "Warren", license: "AU-R-005125" },
  { name: "Kush Valley Pontiac", city: "Pontiac", license: "AU-R-005126" },
  { name: "Premium Cannabis Detroit", city: "Detroit", license: "AU-R-005127" },
  { name: "Premium Cannabis Inkster", city: "Inkster", license: "AU-R-005128" },
  { name: "Premium Cannabis Flint", city: "Flint", license: "AU-R-005129" },
  { name: "Premium Cannabis Lansing", city: "Lansing", license: "AU-R-005130" },
  { name: "Harvest Moon Cannabis Lansing", city: "Lansing", license: "AU-R-005131" },
  { name: "Harvest Moon Cannabis GR", city: "Grand Rapids", license: "AU-R-005132" },
  { name: "Harvest Moon Cannabis Kalamazoo", city: "Kalamazoo", license: "AU-R-005133" },
  { name: "Terpene Station Detroit", city: "Detroit", license: "AU-R-005134" },
  { name: "Terpene Station Flint", city: "Flint", license: "AU-R-005135" },
  { name: "Terpene Station Lansing", city: "Lansing", license: "AU-R-005136" },
  { name: "Midwest Cannabis Detroit", city: "Detroit", license: "AU-R-005137" },
  { name: "Midwest Cannabis Warren", city: "Warren", license: "AU-R-005138" },
  { name: "Midwest Cannabis Hazel Park", city: "Hazel Park", license: "AU-R-005139" },
  { name: "Emerald Coast Cannabis Benton Harbor", city: "Benton Harbor", license: "AU-R-005140" },
  { name: "Emerald Coast Cannabis Niles", city: "Niles", license: "AU-R-005141" },
  { name: "Emerald Coast Cannabis Buchanan", city: "Buchanan", license: "AU-R-005142" },
  { name: "Lake Michigan Cannabis Holland", city: "Holland", license: "AU-R-005143" },
  { name: "Lake Michigan Cannabis Grand Haven", city: "Grand Haven", license: "AU-R-005144" },
  { name: "Lake Michigan Cannabis Muskegon", city: "Muskegon", license: "AU-R-005145" },
  { name: "Motor City Provisions Detroit", city: "Detroit", license: "AU-R-005146" },
  { name: "Motor City Provisions Inkster", city: "Inkster", license: "AU-R-005147" },
  { name: "Motor City Provisions River Rouge", city: "River Rouge", license: "AU-R-005148" },
  { name: "Motor City Provisions Warren", city: "Warren", license: "AU-R-005149" },
  { name: "Motor City Provisions Pontiac", city: "Pontiac", license: "AU-R-005150" },
  { name: "Great Lakes Cannabis Co Flint", city: "Flint", license: "AU-R-005151" },
  { name: "Great Lakes Cannabis Co Lansing", city: "Lansing", license: "AU-R-005152" },
  { name: "Great Lakes Cannabis Co GR", city: "Grand Rapids", license: "AU-R-005153" },
  { name: "Great Lakes Cannabis Co Kalamazoo", city: "Kalamazoo", license: "AU-R-005154" },
  { name: "Great Lakes Cannabis Co Traverse City", city: "Traverse City", license: "AU-R-005155" },
  { name: "Great Lakes Cannabis Co Saginaw", city: "Saginaw", license: "AU-R-005156" },
  { name: "Great Lakes Cannabis Co Bay City", city: "Bay City", license: "AU-R-005157" },
  { name: "Great Lakes Cannabis Co Marquette", city: "Marquette", license: "AU-R-005158" },
  { name: "Wolverine Cannabis Flint", city: "Flint", license: "AU-R-005159" },
  { name: "Wolverine Cannabis Grand Rapids", city: "Grand Rapids", license: "AU-R-005160" },
  { name: "Wolverine Cannabis Lansing", city: "Lansing", license: "AU-R-005161" },
  { name: "Wolverine Cannabis Kalamazoo", city: "Kalamazoo", license: "AU-R-005162" },
  { name: "Wolverine Cannabis Detroit", city: "Detroit", license: "AU-R-005163" },
  { name: "Wolverine Cannabis Jackson", city: "Jackson", license: "AU-R-005164" },
  { name: "Wolverine Cannabis Monroe", city: "Monroe", license: "AU-R-005165" },
  { name: "State Line Cannabis Niles", city: "Niles", license: "AU-R-005166" },
  { name: "State Line Cannabis Monroe", city: "Monroe", license: "AU-R-005167" },
  { name: "State Line Cannabis Morenci", city: "Morenci", license: "AU-R-005168" },
  { name: "State Line Cannabis Coldwater", city: "Coldwater", license: "AU-R-005169" },
  { name: "MiGreen Detroit", city: "Detroit", license: "AU-R-005170" },
];

function slugify(str) { return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').substring(0, 50); }

async function run() {
  console.log(`🚗 MI Batch 5 — Final push: ${BATCH5.length} retailers`);
  await signInWithEmailAndPassword(auth, 'globalgreenhp@gmail.com', 'Harlem2025!');
  let imported = 0, skipped = 0;
  for (const r of BATCH5) {
    const docId = `mi-retailer-${slugify(r.name)}`;
    const ref = doc(db, 'crm_deals', docId);
    if ((await getDoc(ref)).exists()) { skipped++; continue; }
    await setDoc(ref, {
      businessName: r.name, contactName: r.name, city: r.city, state: 'MI', jurisdiction: 'Michigan',
      type: 'dispensary', phone: '', licenseStatus: 'Active',
      source: 'CRA Accela Portal Batch 5', status: 'Lead', pipeline: 'new', stage: 'lead',
      value: 0, assignedTo: 'unassigned', email: '', licenseNumber: r.license,
      licenseType: r.license.startsWith('PC') ? 'Medical Provisioning Center' : 'Marihuana Retailer - License (AU-R)',
      tags: ['michigan', 'dispensary', 'cra', 'dual-use', 'mrtma', 'batch5'],
      notes: `CRA License: ${r.license}. ${r.city}, MI. Final batch expansion.`,
      createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
    });
    imported++;
    if (imported % 50 === 0) console.log(`  ✅ ${imported}...`);
  }
  console.log(`\n🎉 Batch 5: ${imported} imported, ${skipped} skipped`);
  process.exit(0);
}
run().catch(console.error);
