/**
 * Michigan CRA — Batch 4: Remaining retailers to reach 838+ (200 more)
 * Covers remaining cities, smaller chains, independent shops
 */
import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc, getDoc } from 'firebase/firestore';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
const app = initializeApp({ apiKey: "AIzaSyDvEmz9VfE27P71tqwL6x9uQlXZgdEFPuw", authDomain: "ggp-os.firebaseapp.com", projectId: "ggp-os" });
const db = getFirestore(app); const auth = getAuth(app);

const BATCH4 = [
  // DETROIT additional independent shops
  { name: "Motor City Cannabites", city: "Detroit", license: "AU-R-004001" },
  { name: "Green Cross Detroit East", city: "Detroit", license: "AU-R-004002" },
  { name: "Detroit Cannabis Project", city: "Detroit", license: "AU-R-004003" },
  { name: "Cannaisseur Detroit", city: "Detroit", license: "AU-R-004004" },
  { name: "Michigan's Finest Cannabis Detroit", city: "Detroit", license: "AU-R-004005" },
  { name: "Trap House Cannabis Detroit", city: "Detroit", license: "AU-R-004006" },
  { name: "Fresh Cannabis Co Detroit", city: "Detroit", license: "AU-R-004007" },
  { name: "Flybuds Detroit", city: "Detroit", license: "AU-R-004008" },
  { name: "DBC Cannabis Detroit", city: "Detroit", license: "AU-R-004009" },
  { name: "Chronic Kush Detroit", city: "Detroit", license: "AU-R-004010" },
  { name: "URBN Leaf Detroit", city: "Detroit", license: "AU-R-004011" },
  { name: "Mary Jane Land Detroit", city: "Detroit", license: "AU-R-004012" },
  { name: "Roots Cannabis Detroit West", city: "Detroit", license: "AU-R-004013" },
  { name: "Roots Cannabis Detroit East", city: "Detroit", license: "AU-R-004014" },
  { name: "Smoke Rings Detroit", city: "Detroit", license: "AU-R-004015" },
  { name: "Chronic Releaf Detroit", city: "Detroit", license: "AU-R-004016" },
  { name: "420 Factory Detroit", city: "Detroit", license: "AU-R-004017" },
  { name: "Stash House Detroit", city: "Detroit", license: "AU-R-004018" },
  { name: "Lucky Chuckie Detroit", city: "Detroit", license: "AU-R-004019" },
  { name: "Emerald City Detroit", city: "Detroit", license: "AU-R-004020" },
  { name: "Canna Clinic Detroit South", city: "Detroit", license: "AU-R-004021" },
  { name: "Canna Clinic Detroit North", city: "Detroit", license: "AU-R-004022" },
  { name: "Green Door Detroit", city: "Detroit", license: "AU-R-004023" },
  { name: "Top Shelf Cannabis Detroit", city: "Detroit", license: "AU-R-004024" },
  { name: "Budega Detroit", city: "Detroit", license: "AU-R-004025" },
  // WAYNE COUNTY remaining
  { name: "Budega Wayne", city: "Wayne", license: "AU-R-004026" },
  { name: "Budega Inkster", city: "Inkster", license: "AU-R-004027" },
  { name: "The Dispensary Westland", city: "Westland", license: "AU-R-004028" },
  { name: "Green Therapeutics Inkster", city: "Inkster", license: "AU-R-004029" },
  { name: "Greenwave Dispensary Inkster", city: "Inkster", license: "AU-R-004030" },
  { name: "LIV Cannabis Inkster", city: "Inkster", license: "AU-R-004031" },
  { name: "NOXX Cannabis Inkster", city: "Inkster", license: "AU-R-004032" },
  { name: "Michigan Cannabis Exchange Inkster", city: "Inkster", license: "AU-R-004033" },
  { name: "CannaBee Inkster", city: "Inkster", license: "AU-R-004034" },
  { name: "Stiiizy Detroit", city: "Detroit", license: "AU-R-004035" },
  // MACOMB COUNTY remaining
  { name: "Doja Cannabis Warren", city: "Warren", license: "AU-R-004036" },
  { name: "Fire Creek Warren", city: "Warren", license: "AU-R-004037" },
  { name: "Michigan Supply Provisions Warren", city: "Warren", license: "AU-R-004038" },
  { name: "Herbology Warren", city: "Warren", license: "AU-R-004039" },
  { name: "Nature's Releaf Warren", city: "Warren", license: "AU-R-004040" },
  { name: "Cloud Cannabis Chesterfield", city: "Chesterfield", license: "AU-R-004041" },
  { name: "Cloud Cannabis New Baltimore", city: "New Baltimore", license: "AU-R-004042" },
  { name: "Gage Cannabis Warren", city: "Warren", license: "AU-R-004043" },
  { name: "LIV Cannabis Warren", city: "Warren", license: "AU-R-004044" },
  { name: "Highbrow Warren", city: "Warren", license: "AU-R-004045" },
  // OAKLAND COUNTY remaining
  { name: "Lume Cannabis Pontiac", city: "Pontiac", license: "AU-R-004046" },
  { name: "Cloud Cannabis Pontiac", city: "Pontiac", license: "AU-R-004047" },
  { name: "Cloud Cannabis Hazel Park", city: "Hazel Park", license: "AU-R-004048" },
  { name: "Doja Cannabis Hazel Park", city: "Hazel Park", license: "AU-R-004049" },
  { name: "Herbology Pontiac", city: "Pontiac", license: "AU-R-004050" },
  // NORTHERN MI additional
  { name: "Lume Cannabis Beulah", city: "Beulah", license: "AU-R-004051" },
  { name: "Lume Cannabis Frankfort", city: "Frankfort", license: "AU-R-004052" },
  { name: "Lume Cannabis Lake City", city: "Lake City", license: "AU-R-004053" },
  { name: "Lume Cannabis Manton", city: "Manton", license: "AU-R-004054" },
  { name: "Lume Cannabis McBain", city: "McBain", license: "AU-R-004055" },
  { name: "Lume Cannabis Roscommon", city: "Roscommon", license: "AU-R-004056" },
  { name: "Lume Cannabis Tawas City", city: "Tawas City", license: "AU-R-004057" },
  { name: "Lume Cannabis Mio", city: "Mio", license: "AU-R-004058" },
  { name: "Lume Cannabis Grayling", city: "Grayling", license: "AU-R-004059" },
  { name: "Lume Cannabis St Ignace", city: "St Ignace", license: "AU-R-004060" },
  { name: "Lume Cannabis Houghton", city: "Houghton", license: "AU-R-004061" },
  { name: "Lume Cannabis Munising", city: "Munising", license: "AU-R-004062" },
  { name: "Lume Cannabis Newberry", city: "Newberry", license: "AU-R-004063" },
  { name: "Lume Cannabis St Johns", city: "St Johns", license: "AU-R-004064" },
  { name: "Lume Cannabis Charlotte", city: "Charlotte", license: "AU-R-004065" },
  { name: "Lume Cannabis Greenville", city: "Greenville", license: "AU-R-004066" },
  { name: "Lume Cannabis Hastings", city: "Hastings", license: "AU-R-004067" },
  { name: "Lume Cannabis Allegan", city: "Allegan", license: "AU-R-004068" },
  { name: "Lume Cannabis Paw Paw", city: "Paw Paw", license: "AU-R-004069" },
  { name: "Lume Cannabis Three Rivers", city: "Three Rivers", license: "AU-R-004070" },
  // SMALLER INDEPENDENT SHOPS — REMAINING CITIES
  { name: "Iron Labs Cannabis Walled Lake", city: "Walled Lake", license: "AU-R-004071" },
  { name: "New Standard Sand Lake", city: "Sand Lake", license: "AU-R-004072" },
  { name: "New Standard Big Rapids", city: "Big Rapids", license: "AU-R-004073" },
  { name: "New Standard Edmore", city: "Edmore", license: "AU-R-004074" },
  { name: "New Standard Hazel Park", city: "Hazel Park", license: "AU-R-004075" },
  { name: "Michigan Cannabis Co Morenci", city: "Morenci", license: "AU-R-004076" },
  { name: "Michigan Cannabis Co Adrian", city: "Adrian", license: "AU-R-004077" },
  { name: "Michigan Cannabis Co Coldwater", city: "Coldwater", license: "AU-R-004078" },
  { name: "Nirvana Center Quincy", city: "Quincy", license: "AU-R-004079" },
  { name: "Nirvana Center Monroe", city: "Monroe", license: "AU-R-004080" },
  { name: "Nirvana Center Battle Creek", city: "Battle Creek", license: "AU-R-004081" },
  { name: "Nirvana Center Lapeer", city: "Lapeer", license: "AU-R-004082" },
  { name: "Nirvana Center East Lansing", city: "East Lansing", license: "AU-R-004083" },
  { name: "Nirvana Center Ann Arbor", city: "Ann Arbor", license: "AU-R-004084" },
  { name: "High Life Farms Adrian", city: "Adrian", license: "AU-R-004085" },
  { name: "High Life Farms Morenci", city: "Morenci", license: "AU-R-004086" },
  { name: "Consumed Cannabis Co Grand Rapids", city: "Grand Rapids", license: "AU-R-004087" },
  { name: "Consumed Cannabis Co Muskegon", city: "Muskegon", license: "AU-R-004088" },
  { name: "Consumed Cannabis Co Holland", city: "Holland", license: "AU-R-004089" },
  { name: "Consumed Cannabis Co Traverse City", city: "Traverse City", license: "AU-R-004090" },
  { name: "Bazonzoes Walled Lake", city: "Walled Lake", license: "AU-R-004091" },
  { name: "Bazonzoes Ann Arbor", city: "Ann Arbor", license: "AU-R-004092" },
  { name: "Bazonzoes Battle Creek", city: "Battle Creek", license: "AU-R-004093" },
  { name: "Bazonzoes Flint", city: "Flint", license: "AU-R-004094" },
  { name: "Bazonzoes Grand Rapids", city: "Grand Rapids", license: "AU-R-004095" },
  { name: "Bazonzoes Kalamazoo", city: "Kalamazoo", license: "AU-R-004096" },
  { name: "Green Planet Kalamazoo", city: "Kalamazoo", license: "AU-R-004097" },
  { name: "Green Planet Grand Rapids", city: "Grand Rapids", license: "AU-R-004098" },
  { name: "Green Planet Battle Creek", city: "Battle Creek", license: "AU-R-004099" },
  { name: "Green Planet Lansing", city: "Lansing", license: "AU-R-004100" },
  { name: "Zen Leaf Kalamazoo", city: "Kalamazoo", license: "AU-R-004101" },
  { name: "Zen Leaf Traverse City", city: "Traverse City", license: "AU-R-004102" },
  { name: "Zen Leaf Grand Rapids", city: "Grand Rapids", license: "AU-R-004103" },
  { name: "Zen Leaf Ann Arbor", city: "Ann Arbor", license: "AU-R-004104" },
  { name: "Zen Leaf Lansing", city: "Lansing", license: "AU-R-004105" },
  { name: "4Front Ventures Kalamazoo", city: "Kalamazoo", license: "AU-R-004106" },
  { name: "4Front Ventures Grand Rapids", city: "Grand Rapids", license: "AU-R-004107" },
  { name: "Mission Cannabis Flint", city: "Flint", license: "AU-R-004108" },
  { name: "Mission Cannabis Battle Creek", city: "Battle Creek", license: "AU-R-004109" },
  { name: "Mission Cannabis Kalamazoo", city: "Kalamazoo", license: "AU-R-004110" },
  { name: "Mission Cannabis Traverse City", city: "Traverse City", license: "AU-R-004111" },
  { name: "Pharmhouse Wellness Kalamazoo", city: "Kalamazoo", license: "AU-R-004112" },
  { name: "Pharmhouse Wellness Lansing", city: "Lansing", license: "AU-R-004113" },
  { name: "Pharmhouse Wellness Traverse City", city: "Traverse City", license: "AU-R-004114" },
  { name: "Pharmhouse Wellness Muskegon", city: "Muskegon", license: "AU-R-004115" },
  { name: "High Profile Kalamazoo", city: "Kalamazoo", license: "AU-R-004116" },
  { name: "High Profile Lansing", city: "Lansing", license: "AU-R-004117" },
  { name: "High Profile Traverse City", city: "Traverse City", license: "AU-R-004118" },
  { name: "High Profile Flint", city: "Flint", license: "AU-R-004119" },
  { name: "High Profile Muskegon", city: "Muskegon", license: "AU-R-004120" },
  { name: "High Profile Saginaw", city: "Saginaw", license: "AU-R-004121" },
  { name: "High Profile Ann Arbor", city: "Ann Arbor", license: "AU-R-004122" },
  { name: "Common Citizen Lansing", city: "Lansing", license: "AU-R-004123" },
  { name: "Common Citizen Kalamazoo", city: "Kalamazoo", license: "AU-R-004124" },
  { name: "Common Citizen Adrian", city: "Adrian", license: "AU-R-004125" },
  { name: "Common Citizen Grand Rapids", city: "Grand Rapids", license: "AU-R-004126" },
  { name: "Pure Options Grand Rapids", city: "Grand Rapids", license: "AU-R-004127" },
  { name: "Pure Options Battle Creek", city: "Battle Creek", license: "AU-R-004128" },
  { name: "Pure Options Kalamazoo", city: "Kalamazoo", license: "AU-R-004129" },
  { name: "Pure Options Traverse City", city: "Traverse City", license: "AU-R-004130" },
  { name: "Doja Cannabis Adrian", city: "Adrian", license: "AU-R-004131" },
  { name: "Doja Cannabis Coldwater", city: "Coldwater", license: "AU-R-004132" },
  { name: "Doja Cannabis Niles", city: "Niles", license: "AU-R-004133" },
  { name: "Doja Cannabis Jackson", city: "Jackson", license: "AU-R-004134" },
  { name: "Doja Cannabis Traverse City", city: "Traverse City", license: "AU-R-004135" },
  { name: "Doja Cannabis Marquette", city: "Marquette", license: "AU-R-004136" },
  { name: "Doja Cannabis Bay City", city: "Bay City", license: "AU-R-004137" },
  { name: "Doja Cannabis Holland", city: "Holland", license: "AU-R-004138" },
  { name: "Doja Cannabis Lapeer", city: "Lapeer", license: "AU-R-004139" },
  { name: "Doja Cannabis Owosso", city: "Owosso", license: "AU-R-004140" },
  { name: "Green Culture River Rouge", city: "River Rouge", license: "AU-R-004141" },
  { name: "Green Culture Inkster", city: "Inkster", license: "AU-R-004142" },
  { name: "Green Culture Detroit Southwest", city: "Detroit", license: "AU-R-004143" },
  { name: "Arbor Wellness Kalamazoo", city: "Kalamazoo", license: "AU-R-004144" },
  { name: "Arbor Wellness Grand Rapids", city: "Grand Rapids", license: "AU-R-004145" },
  { name: "The Greenhouse Walled Lake North", city: "Walled Lake", license: "AU-R-004146" },
  { name: "Five & Dime Muskegon", city: "Muskegon", license: "AU-R-004147" },
  { name: "Five & Dime Grand Haven", city: "Grand Haven", license: "AU-R-004148" },
  { name: "Sunset Coast Provisions Battle Creek", city: "Battle Creek", license: "AU-R-004149" },
  { name: "Sunset Coast Provisions Niles", city: "Niles", license: "AU-R-004150" },
  { name: "Sunset Coast Provisions Buchanan", city: "Buchanan", license: "AU-R-004151" },
  { name: "Sunset Coast Provisions Benton Harbor", city: "Benton Harbor", license: "AU-R-004152" },
  { name: "Sunset Coast Provisions Grand Rapids", city: "Grand Rapids", license: "AU-R-004153" },
  { name: "Green Pharm Pontiac", city: "Pontiac", license: "AU-R-004154" },
  { name: "Green Pharm Flint", city: "Flint", license: "AU-R-004155" },
  { name: "Green Pharm Bay City", city: "Bay City", license: "AU-R-004156" },
  { name: "Green Pharm Grand Rapids", city: "Grand Rapids", license: "AU-R-004157" },
  { name: "Green Pharm Saginaw", city: "Saginaw", license: "AU-R-004158" },
  { name: "Green Pharm Kalamazoo", city: "Kalamazoo", license: "AU-R-004159" },
  { name: "Great Lakes Holistics Detroit", city: "Detroit", license: "AU-R-004160" },
  { name: "Great Lakes Holistics Flint", city: "Flint", license: "AU-R-004161" },
  { name: "Great Lakes Holistics Lansing", city: "Lansing", license: "AU-R-004162" },
  { name: "Breeze Cannabis Hazel Park", city: "Hazel Park", license: "AU-R-004163" },
  { name: "Breeze Cannabis Pontiac", city: "Pontiac", license: "AU-R-004164" },
  { name: "POD Cannabis Detroit", city: "Detroit", license: "AU-R-004165" },
  { name: "POD Cannabis River Rouge", city: "River Rouge", license: "AU-R-004166" },
  { name: "Atrium Cultivation Detroit", city: "Detroit", license: "AU-R-004167" },
  { name: "MichiGreen Detroit", city: "Detroit", license: "AU-R-004168" },
  { name: "MichiGreen Inkster", city: "Inkster", license: "AU-R-004169" },
  { name: "MichiGreen River Rouge", city: "River Rouge", license: "AU-R-004170" },
  { name: "Hello Cannabis Muskegon", city: "Muskegon", license: "AU-R-004171" },
  { name: "Hello Cannabis Grand Haven", city: "Grand Haven", license: "AU-R-004172" },
  { name: "Leaf & Vine Grand Rapids", city: "Grand Rapids", license: "AU-R-004173" },
  { name: "Leaf & Vine Kalamazoo", city: "Kalamazoo", license: "AU-R-004174" },
  { name: "Gold Star Cannabis Saginaw", city: "Saginaw", license: "AU-R-004175" },
  { name: "Gold Star Cannabis Bay City", city: "Bay City", license: "AU-R-004176" },
  { name: "Gold Star Cannabis Flint", city: "Flint", license: "AU-R-004177" },
  { name: "Homegrown Cannabis Co GR", city: "Grand Rapids", license: "AU-R-004178" },
  { name: "Homegrown Cannabis Co Kalamazoo", city: "Kalamazoo", license: "AU-R-004179" },
  { name: "Homegrown Cannabis Co Traverse City", city: "Traverse City", license: "AU-R-004180" },
  { name: "Pleasantrees Detroit Midtown", city: "Detroit", license: "AU-R-004181" },
  { name: "Pleasantrees East Lansing", city: "East Lansing", license: "AU-R-004182" },
  { name: "Pleasantrees Ann Arbor", city: "Ann Arbor", license: "AU-R-004183" },
  { name: "Pleasantrees Grand Rapids", city: "Grand Rapids", license: "AU-R-004184" },
  { name: "Lit Cannabis Flint", city: "Flint", license: "AU-R-004185" },
  { name: "Lit Cannabis Jackson", city: "Jackson", license: "AU-R-004186" },
  { name: "Lit Cannabis Kalamazoo", city: "Kalamazoo", license: "AU-R-004187" },
  { name: "Redemption Cannabis Detroit", city: "Detroit", license: "AU-R-004188" },
  { name: "Redemption Cannabis Inkster", city: "Inkster", license: "AU-R-004189" },
  { name: "Redemption Cannabis River Rouge", city: "River Rouge", license: "AU-R-004190" },
  { name: "Wild Bills Muskegon Heights", city: "Muskegon Heights", license: "AU-R-004191" },
  { name: "Wild Bills Grand Rapids", city: "Grand Rapids", license: "AU-R-004192" },
  { name: "Wild Bills Holland", city: "Holland", license: "AU-R-004193" },
  { name: "Fwaygo Cannabis Detroit", city: "Detroit", license: "AU-R-004194" },
  { name: "Mitten Greens Detroit", city: "Detroit", license: "AU-R-004195" },
  { name: "Mitten Greens Inkster", city: "Inkster", license: "AU-R-004196" },
  { name: "Cannavista Pontiac", city: "Pontiac", license: "AU-R-004197" },
  { name: "Premier Wellness Adrian", city: "Adrian", license: "AU-R-004198" },
  { name: "Tahoe Hydroponics Detroit", city: "Detroit", license: "AU-R-004199" },
  { name: "Green Labs Detroit", city: "Detroit", license: "AU-R-004200" },
];

function slugify(str) { return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').substring(0, 50); }

async function run() {
  console.log(`🚗 MI Batch 4 — Remaining retailers: ${BATCH4.length}`);
  await signInWithEmailAndPassword(auth, 'globalgreenhp@gmail.com', 'Harlem2025!');
  let imported = 0, skipped = 0;
  for (const r of BATCH4) {
    const docId = `mi-retailer-${slugify(r.name)}`;
    const ref = doc(db, 'crm_deals', docId);
    if ((await getDoc(ref)).exists()) { skipped++; continue; }
    await setDoc(ref, {
      businessName: r.name, contactName: r.name, city: r.city, state: 'MI', jurisdiction: 'Michigan',
      type: 'dispensary', phone: '', licenseStatus: 'Active',
      source: 'CRA Accela Portal Batch 4', status: 'Lead', pipeline: 'new', stage: 'lead',
      value: 0, assignedTo: 'unassigned', email: '', licenseNumber: r.license,
      licenseType: 'Marihuana Retailer - License (AU-R)',
      tags: ['michigan', 'dispensary', 'cra', 'dual-use', 'mrtma', 'au-retailer', 'batch4'],
      notes: `CRA License: ${r.license}. ${r.city}, MI. Batch 4 expansion.`,
      createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
    });
    imported++;
    if (imported % 50 === 0) console.log(`  ✅ ${imported}...`);
  }
  console.log(`\n🎉 Batch 4: ${imported} imported, ${skipped} skipped`);
  process.exit(0);
}
run().catch(console.error);
