const fs = require('fs');

// Compliance data from user's spreadsheet
const compliance = {
  "Alabama": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "Alabama Medical Cannabis Commission", compliancePage: "https://amcc.alabama.gov/", checklistItems: ["Licensing","Seed-to-sale tracking","Testing","Packaging","Advertising"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Alaska": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Alaska Alcohol & Marijuana Control Office", compliancePage: "https://www.commerce.alaska.gov/web/amco/", checklistItems: ["License","Inventory tracking","Testing","Labeling","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Arizona": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Arizona Department of Health Services", compliancePage: "https://www.azdhs.gov/licensing/medical-marijuana/", checklistItems: ["Licensing","Testing","Product rules","Security","Records"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Arkansas": { adultUseStatus: "No", medicalStatus: "Yes", regulator: "Arkansas Medical Marijuana Commission", compliancePage: "https://www.dfa.arkansas.gov/office/medical-marijuana-commission/", checklistItems: ["Licensing","Labeling","Testing","Track-and-trace","Inspections"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "California": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "California Department of Cannabis Control", compliancePage: "https://www.cannabis.ca.gov/", checklistItems: ["Cultivator self-inspection","Testing","Packaging","Labor compliance","Track-and-trace"], complianceSource: "https://www.cannabis.ca.gov/posts/cannabis-cultivator-self-inspection-checklist/" },
  "Colorado": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Colorado Marijuana Enforcement Division", compliancePage: "https://med.colorado.gov/", checklistItems: ["License","Inventory","Testing","Advertising","Transport"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Connecticut": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Connecticut Department of Consumer Protection", compliancePage: "https://portal.ct.gov/cannabis/", checklistItems: ["Licensing","Track-and-trace","Testing","Labeling","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Delaware": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Delaware Cannabis Control Office", compliancePage: "https://omc.delaware.gov/", checklistItems: ["Licensing","Testing","Packaging","Records","Security"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "District Of Columbia": { adultUseStatus: "Yes/limited", medicalStatus: "Yes", regulator: "DC Alcoholic Beverage and Cannabis Administration", compliancePage: "https://abca.dc.gov/", checklistItems: ["Medical authorization","Dispensing rules","Records","Testing"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Florida": { adultUseStatus: "No", medicalStatus: "Yes", regulator: "Florida Department of Health OMMU", compliancePage: "https://knowthefactsmmj.com/", checklistItems: ["Medical authorization","Product rules","Testing","Dispensing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Georgia": { adultUseStatus: "No/limited", medicalStatus: "Limited", regulator: "Georgia Access to Medical Cannabis Commission", compliancePage: "https://www.gmcc.ga.gov/", checklistItems: ["License","Low-THC limits","Dispensing rules","Records"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Hawaii": { adultUseStatus: "No", medicalStatus: "Yes", regulator: "Hawaii Department of Health", compliancePage: "https://health.hawaii.gov/medicalcannabis/", checklistItems: ["Medical licensing","Lab testing","Packaging","Dispensary rules"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Idaho": { adultUseStatus: "No", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "Illinois": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Illinois cannabis regulator (IDFPR)", compliancePage: "https://dph.illinois.gov/topics-services/prevention-wellness/medical-cannabis.html", checklistItems: ["Adult-use licensing","Testing","Labeling","Equity programs","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Indiana": { adultUseStatus: "No", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "Iowa": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "Iowa DHHS", compliancePage: "https://hhs.iowa.gov/health-prevention/medical-cannabis/", checklistItems: ["Medical product limits","Testing","Labeling","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Kansas": { adultUseStatus: "Just legalized Feb/Mar 2026", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework yet"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "Kentucky": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "Kentucky Cabinet for Health and Family Services", compliancePage: "https://kymedcan.ky.gov/", checklistItems: ["Licensing","Testing","Packaging","Seed-to-sale","Dispensing"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Louisiana": { adultUseStatus: "No", medicalStatus: "Yes", regulator: "Louisiana Department of Health", compliancePage: "https://ldh.la.gov/page/medical-marijuana", checklistItems: ["Medical cultivation/processing","Testing","Product rules","Retailer permits"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Maine": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Maine Office of Cannabis Policy", compliancePage: "https://www.maine.gov/dafs/ocp/", checklistItems: ["License","Testing","Packaging","Labeling","Labor","Tax"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Maryland": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Maryland Cannabis Administration", compliancePage: "https://cannabis.maryland.gov/", checklistItems: ["Licensing","Testing","Advertising","Track-and-trace","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Massachusetts": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Massachusetts Cannabis Control Commission", compliancePage: "https://masscannabiscontrol.com/", checklistItems: ["License","Testing","Security","Recalls","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Michigan": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Michigan Cannabis Regulatory Agency", compliancePage: "https://www.michigan.gov/cra/", checklistItems: ["License","Testing","METRC","Packaging","Advertising"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Minnesota": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Minnesota Office of Cannabis Management", compliancePage: "https://mn.gov/ocm/", checklistItems: ["Licensing","Testing","Packaging","Local approvals"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Mississippi": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "Mississippi Medical Cannabis Program", compliancePage: "https://www.mmcp.ms.gov/", checklistItems: ["Medical licensing","Testing","Labeling","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Missouri": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Missouri Division of Cannabis Regulation", compliancePage: "https://health.mo.gov/safety/cannabis/", checklistItems: ["License","Testing","Packaging","Track-and-trace","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Montana": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Montana Cannabis Control Division", compliancePage: "https://revenue.mt.gov/", checklistItems: ["License","Testing","Labeling","Inventory","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Nebraska": { adultUseStatus: "Just legalized Mar/Apr 2026", medicalStatus: "No comprehensive program", regulator: "Nebraska Medical Cannabis Commission", compliancePage: "https://lcc.nebraska.gov/medical-cannabis/", checklistItems: ["Cultivator licensing priority","Residency requirements","Background checks"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "Nevada": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Nevada Cannabis Compliance Board", compliancePage: "https://ccb.nv.gov/", checklistItems: ["License","Testing","Packaging","Security","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "New Hampshire": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "New Hampshire DHHS", compliancePage: "https://www.dhhs.nh.gov/programs-services/population-health/therapeutic-cannabis/", checklistItems: ["Medical cultivation/dispensary rules","Testing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "New Jersey": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "New Jersey Cannabis Regulatory Commission", compliancePage: "https://www.nj.gov/cannabis/", checklistItems: ["License","Testing","Labeling","Labor","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "New Mexico": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "New Mexico Cannabis Control Division", compliancePage: "https://www.rld.nm.gov/cannabis/", checklistItems: ["License","Testing","Packaging","Track-and-trace"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "New York": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "New York Office of Cannabis Management", compliancePage: "https://cannabis.ny.gov/", checklistItems: ["License","Testing","Labeling","Marketing","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "North Carolina": { adultUseStatus: "No", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "North Dakota": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "North Dakota DHHS", compliancePage: "https://mmregistration.health.nd.gov/", checklistItems: ["Medical licensing","Testing","Dispensing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Ohio": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Ohio Division of Cannabis Control", compliancePage: "https://com.ohio.gov/divisions-and-programs/cannabis-control", checklistItems: ["License","Testing","Packaging","Track-and-trace","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Oklahoma": { adultUseStatus: "No", medicalStatus: "Yes", regulator: "Oklahoma Medical Marijuana Authority", compliancePage: "https://oklahoma.gov/omma/businesses/inspections-and-compliance.html", checklistItems: ["Post-approval checklist","OBNDD registration","METRC","Tax compliance","Fire/safety","Water compliance"], complianceSource: "https://oklahoma.gov/omma/businesses/inspections-and-compliance.html" },
  "Oregon": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Oregon Liquor and Cannabis Commission", compliancePage: "https://www.oregon.gov/olcc/", checklistItems: ["License","Testing","Packaging","Labeling","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Pennsylvania": { adultUseStatus: "No", medicalStatus: "Yes", regulator: "Pennsylvania Department of Health", compliancePage: "https://www.pa.gov/services/health/register-for-the-medical-marijuana-program", checklistItems: ["Medical licensing","Testing","Dispensing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Rhode Island": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Rhode Island Cannabis Control Commission", compliancePage: "https://dbr.ri.gov/cannabis/", checklistItems: ["License","Testing","Labeling","Tax","Inspections"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "South Carolina": { adultUseStatus: "No", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "South Dakota": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "South Dakota Department of Health", compliancePage: "https://medcannabis.sd.gov/", checklistItems: ["Medical licensing","Testing","Dispensing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Tennessee": { adultUseStatus: "No", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "Texas": { adultUseStatus: "No/limited", medicalStatus: "Limited", regulator: "Texas Department of Public Safety", compliancePage: "https://www.texas.gov/health-services/texas-medical-marijuana/", checklistItems: ["Low-THC product rules","Licensing","Testing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Utah": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "Utah Department of Health and Human Services", compliancePage: "https://medicalcannabis.utah.gov/", checklistItems: ["Medical licensing","Testing","Labeling","Dispensing"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Vermont": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Vermont Cannabis Control Board", compliancePage: "https://ccb.vermont.gov/", checklistItems: ["License","Testing","Packaging","Labeling","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Virginia": { adultUseStatus: "Yes/limited retail", medicalStatus: "Yes", regulator: "Virginia Cannabis Control Authority", compliancePage: "https://cca.virginia.gov/", checklistItems: ["License framework","Retail status","Labeling","Records"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "Washington": { adultUseStatus: "Yes", medicalStatus: "Yes", regulator: "Washington State Liquor and Cannabis Board", compliancePage: "https://lcb.wa.gov/", checklistItems: ["License","Testing","Packaging","Traceability","Taxes"], complianceSource: "https://www.nsc.org/cannabis-regulations" },
  "West Virginia": { adultUseStatus: "No/limited", medicalStatus: "Yes", regulator: "West Virginia Office of Medical Cannabis", compliancePage: "https://omc.wv.gov/", checklistItems: ["Medical licensing","Testing","Dispensing","Records"], complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws" },
  "Wisconsin": { adultUseStatus: "Just legalized March 2026", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework yet"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
  "Wyoming": { adultUseStatus: "No", medicalStatus: "No comprehensive program", regulator: "State law only", compliancePage: "", checklistItems: ["No operational cannabis business framework"], complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction" },
};

// Read the file
let content = fs.readFileSync('src/stateResources.ts', 'utf8');

let changes = 0;
for (const [state, data] of Object.entries(compliance)) {
  // Find the state entry and add compliance fields before the closing }
  // Look for the pattern: "StateName": {\n ... abbreviation: "XX"\n  },
  const abbrevPattern = new RegExp(`("${state.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}":\\s*\\{[\\s\\S]*?abbreviation:\\s*"[A-Z]{2}")`, 'm');
  const match = content.match(abbrevPattern);
  if (match) {
    const complianceFields = `,\n    adultUseStatus: ${JSON.stringify(data.adultUseStatus)},\n    medicalStatus: ${JSON.stringify(data.medicalStatus)},\n    regulator: ${JSON.stringify(data.regulator)},\n    compliancePage: ${JSON.stringify(data.compliancePage)},\n    checklistItems: ${JSON.stringify(data.checklistItems)},\n    complianceSource: ${JSON.stringify(data.complianceSource)}`;
    content = content.replace(match[1], match[1] + complianceFields);
    changes++;
  } else {
    console.log(`WARNING: Could not find entry for "${state}"`);
  }
}

fs.writeFileSync('src/stateResources.ts', content);
console.log(`Injected compliance data into ${changes} states`);
