// ═══════════════════════════════════════════════════════════════════════════════
// GGP-OS Nationwide State Cannabis Resources Database
// All 50 States + District of Columbia
// ═══════════════════════════════════════════════════════════════════════════════

export interface StateResource {
  program: string;
  patientPortal: string;
  businessPortal: string;
  guide: string;
  resources: string;
  status?: string;
  year?: string;
  conditions?: string[];
  abbreviation?: string;
  // Compliance & Regulatory fields
  adultUseStatus?: string;
  medicalStatus?: string;
  regulator?: string;
  compliancePage?: string;
  checklistItems?: string[];
  complianceSource?: string;
}

export const STATE_RESOURCES: Record<string, StateResource> = {
  "Alabama": {
    program: "Alabama Medical Cannabis Commission",
    patientPortal: "https://amcc.alabama.gov/patients/",
    businessPortal: "https://amcc.alabama.gov/cannabis-business-applicants-2/",
    guide: "",
    resources: "https://256today.com/north-alabama-physicians-among-first-certified-to-qualify-medical-cannabis-patients/",
    status: "Not Yet Operational", year: "2021", abbreviation: "AL",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "Alabama Medical Cannabis Commission",
    compliancePage: "https://amcc.alabama.gov/",
    checklistItems: ["Licensing","Seed-to-sale tracking","Testing","Packaging","Advertising"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws",
    conditions: ["Autism Spectrum Disorder (ASD)","Cancer-related cachexia, nausea or vomiting, weight loss, or chronic pain","Crohn's Disease","Depression","Epilepsy or a condition causing seizures","HIV/AIDS-related nausea or weight loss","Panic disorder","Parkinson's disease","Persistent nausea that is not significantly responsive to traditional treatment","Post Traumatic Stress Disorder (PTSD)","Sickle Cell Anemia","Spasticity associated with a motor neuron disease, including ALS","Spasticity associated with Multiple Sclerosis or a spinal cord injury","Terminal illness","Tourette's Syndrome","A condition causing chronic or intractable pain"]
  },
  "Alaska": {
    program: "https://www.commerce.alaska.gov/web/amco/home.aspx",
    patientPortal: "Marijuana Registry Application",
    businessPortal: "https://accis.elicense365.com/#",
    guide: "https://www.commerce.alaska.gov/web/Portals/9/pub/ABC/AlcoholFAQ/Accessing%20the%20Public%20Search%20on%20AK-ACCIS.pdf",
    resources: "https://www.mpp.org/states/alaska/?state=AK",
    status: "Operational", year: "1998", abbreviation: "AK",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Alaska Alcohol & Marijuana Control Office",
    compliancePage: "https://www.commerce.alaska.gov/web/amco/",
    checklistItems: ["License","Inventory tracking","Testing","Labeling","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations",
    conditions: ["Cachexia","Cancer","Chronic Pain","Glaucoma","HIV or AIDS","Multiple Sclerosis","Nausea","Seizures"]
  },
  "Arizona": {
    program: "AZDHS | Public Health Licensing - Medical Marijuana",
    patientPortal: "https://individual-licensing.azdhs.gov/s/login/?ec=302&startURL=%2Fs%2F",
    businessPortal: "https://www.azdhs.gov/licensing/medical-marijuana/",
    guide: "",
    resources: "https://www.mpp.org/states/arizona/?state=AZ",
    status: "Operational", year: "2011", abbreviation: "AZ",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Arizona Department of Health Services",
    compliancePage: "https://www.azdhs.gov/licensing/medical-marijuana/",
    checklistItems: ["Licensing","Testing","Product rules","Security","Records"],
    complianceSource: "https://www.nsc.org/cannabis-regulations",
    conditions: ["Alzheimer's Disease","Amyotrophic Lateral Sclerosis (Lou Gehrig's disease)","Cachexia or wasting syndrome","Cancer","Chronic pain","Crohn's Disease","Glaucoma","Hepatitis C","HIV or AIDS","Nausea","Persistent Muscle Spasms","PTSD","Seizures"]
  },
  "Arkansas": {
    program: "Medical Marijuana Program",
    patientPortal: "https://mmj.adh.arkansas.gov/",
    businessPortal: "https://www.dfa.arkansas.gov/office/medical-marijuana-commission/applications-and-forms/",
    guide: "https://www.dfa.arkansas.gov/wp-content/uploads/00101_-_00118_Redacted.pdf",
    resources: "https://www.mpp.org/states/arkansas/?state=AR",
    status: "Operational", year: "2016", abbreviation: "AR",
    adultUseStatus: "No",
    medicalStatus: "Yes",
    regulator: "Arkansas Medical Marijuana Commission",
    compliancePage: "https://www.dfa.arkansas.gov/office/medical-marijuana-commission/",
    checklistItems: ["Licensing","Labeling","Testing","Track-and-trace","Inspections"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws",
    conditions: ["ALS","Alzheimer's disease","Cachexia or wasting syndrome","Cancer","Chronic or debilitating disease","Crohn's disease","Fibromyalgia","Glaucoma","Hepatitis C","HIV/AIDS","Intractable pain","Multiple sclerosis","Peripheral neuropathy","PTSD","Seizures","Severe arthritis","Severe nausea","Severe and persistent muscle spasms","Tourette's syndrome","Ulcerative colitis","Any medical condition approved by the Department of Health"]
  },
  "California": {
    program: "https://www.cannabis.ca.gov/",
    patientPortal: "https://www.cdph.ca.gov/Programs/CHSI/Pages/MMICP.aspx",
    businessPortal: "https://www.cannabis.ca.gov/applicants/",
    guide: "",
    resources: "https://www.mpp.org/states/california/?state=CA",
    status: "Operational", year: "1996", abbreviation: "CA",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "California Department of Cannabis Control",
    compliancePage: "https://www.cannabis.ca.gov/",
    checklistItems: ["Cultivator self-inspection","Testing","Packaging","Labor compliance","Track-and-trace"],
    complianceSource: "https://www.cannabis.ca.gov/posts/cannabis-cultivator-self-inspection-checklist/",
    conditions: ["Anorexia","Arthritis","Cachexia","Cancer","Chronic Pain","HIV or AIDS","Glaucoma","Migraine","Persistent Muscle Spasms","Severe Nausea","Seizures","Any debilitating illness deemed appropriate"]
  },
  "Colorado": {
    program: "https://cdphe.colorado.gov/",
    patientPortal: "https://cdphe.colorado.gov/medical-marijuana-registry-patients",
    businessPortal: "https://med.colorado.gov/marijuana-business-owner-license-application",
    guide: "https://med.colorado.gov/regulated-marijuana-business-license-application",
    resources: "https://www.mpp.org/states/colorado/?state=CO",
    abbreviation: "CO",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Colorado Marijuana Enforcement Division",
    compliancePage: "https://med.colorado.gov/",
    checklistItems: ["License","Inventory","Testing","Advertising","Transport"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Connecticut": {
    program: "https://portal.ct.gov/cannabis/medical-marijuana-program?language=en_US",
    patientPortal: "https://biznet.ct.gov/AccountMaint/Login.aspx",
    businessPortal: "https://portal.ct.gov/cannabis/knowledge-base/articles/licensing/licensing-home-page?language=en_US",
    guide: "https://portal.ct.gov/cannabis/knowledge-base/articles/mmp/register-for-a-medical-marijuana-card?language=en_US",
    resources: "https://www.mpp.org/states/connecticut/?state=CT",
    abbreviation: "CT",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Connecticut Department of Consumer Protection",
    compliancePage: "https://portal.ct.gov/cannabis/",
    checklistItems: ["Licensing","Track-and-trace","Testing","Labeling","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Delaware": {
    program: "https://omc.delaware.gov/medical/index.shtml?dc=appProc",
    patientPortal: "https://patients.de.biotr.ac/registration",
    businessPortal: "https://omc.delaware.gov/adult/licensing/contentFolder/pdfs/matrix.pdf?cache=1773361497392",
    guide: "https://omc.delaware.gov/adult/licensing/contentFolder/pdfs/matrix.pdf?cache=1773361497392",
    resources: "https://www.mpp.org/states/delaware/?state=DE",
    abbreviation: "DE",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Delaware Cannabis Control Office",
    compliancePage: "https://omc.delaware.gov/",
    checklistItems: ["Licensing","Testing","Packaging","Records","Security"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "District Of Columbia": {
    program: "https://abca.dc.gov/page/patients%E2%80%94dc-residents",
    patientPortal: "https://octo.quickbase.com/db/bscn22va8?a=dbpage&pageid=23",
    businessPortal: "https://abca.dc.gov/page/medical-cannabis-program#gsc.tab=0",
    guide: "",
    resources: "https://www.mpp.org/states/district-of-columbia/?state=DC",
    abbreviation: "DC",
    adultUseStatus: "Yes/limited",
    medicalStatus: "Yes",
    regulator: "DC Alcoholic Beverage and Cannabis Administration",
    compliancePage: "https://abca.dc.gov/",
    checklistItems: ["Medical authorization","Dispensing rules","Records","Testing"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Florida": {
    program: "https://mmuregistry.flhealth.gov/spa/",
    patientPortal: "https://mmuregistry.flhealth.gov/spa/login",
    businessPortal: "https://knowthefactsmmj.com/wp-content/uploads/_documents/form-dh8013-ommu-042018-application-for-medical-marijuana-treatment-center-registration.pdf",
    guide: "",
    resources: "https://www.mpp.org/states/florida/?state=FL",
    abbreviation: "FL",
    adultUseStatus: "No",
    medicalStatus: "Yes",
    regulator: "Florida Department of Health OMMU",
    compliancePage: "https://knowthefactsmmj.com/",
    checklistItems: ["Medical authorization","Product rules","Testing","Dispensing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Georgia": {
    program: "https://www.gmcc.ga.gov/home",
    patientPortal: "https://dph.georgia.gov/low-thc-oil-registry/patients-and-caregivers",
    businessPortal: "https://www.gmcc.ga.gov/licensing/dispensing-license",
    guide: "https://drive.google.com/file/d/1fE7ssVack5s48xVXcI_yLKZyPoqoIunm/view",
    resources: "https://www.mpp.org/states/georgia/?state=GA",
    abbreviation: "GA",
    adultUseStatus: "No/limited",
    medicalStatus: "Limited",
    regulator: "Georgia Access to Medical Cannabis Commission",
    compliancePage: "https://www.gmcc.ga.gov/",
    checklistItems: ["License","Low-THC limits","Dispensing rules","Records"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Hawaii": {
    program: "https://medmj.ehawaii.gov/medmj/welcome",
    patientPortal: "https://id.hawaii.gov/am/XUI/?realm=/alpha&authIndexType=service&authIndexValue=myHawaii%20Secure%20Login",
    businessPortal: "https://health.hawaii.gov/medicalcannabis/",
    guide: "",
    resources: "https://www.mpp.org/states/hawaii/?state=HI",
    abbreviation: "HI",
    adultUseStatus: "No",
    medicalStatus: "Yes",
    regulator: "Hawaii Department of Health",
    compliancePage: "https://health.hawaii.gov/medicalcannabis/",
    checklistItems: ["Medical licensing","Lab testing","Packaging","Dispensary rules"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Idaho": {
    program: "https://idahocannabis.org/medical",
    patientPortal: "https://idahocannabis.org/medical",
    businessPortal: "https://agri.idaho.gov/",
    guide: "https://agri.idaho.gov/",
    resources: "https://www.mpp.org/states/idaho/?state=ID",
    abbreviation: "ID",
    adultUseStatus: "No",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "Illinois": {
    program: "https://dph.illinois.gov/topics-services/prevention-wellness/medical-cannabis.html",
    patientPortal: "https://ilogin.illinois.gov/",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/illinois/?state=IL",
    abbreviation: "IL",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Illinois cannabis regulator (IDFPR)",
    compliancePage: "https://dph.illinois.gov/topics-services/prevention-wellness/medical-cannabis.html",
    checklistItems: ["Adult-use licensing","Testing","Labeling","Equity programs","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Indiana": {
    program: "https://indianacannabis.org/medical",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/indiana/?state=IN",
    abbreviation: "IN",
    adultUseStatus: "No",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "Iowa": {
    program: "https://hhs.iowa.gov/health-prevention/medical-cannabis/patients-caregivers",
    patientPortal: "https://idph.my.salesforce-sites.com/IowaReg",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/iowa/?state=IA",
    abbreviation: "IA",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "Iowa DHHS",
    compliancePage: "https://hhs.iowa.gov/health-prevention/medical-cannabis/",
    checklistItems: ["Medical product limits","Testing","Labeling","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Kansas": {
    program: "https://kansasstatecannabis.org/medical",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/kansas/?state=KS",
    abbreviation: "KS",
    adultUseStatus: "Just legalized Feb/Mar 2026",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework yet"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "Kentucky": {
    program: "https://kymedcan.ky.gov/Pages/index.aspx",
    patientPortal: "https://kymedcan.ky.gov/patients-and-caregivers/Pages/default.aspx",
    businessPortal: "https://kymedcan.ky.gov/businesses/Pages/default.aspx",
    guide: "",
    resources: "https://www.mpp.org/states/kentucky/?state=KY",
    abbreviation: "KY",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "Kentucky Cabinet for Health and Family Services",
    compliancePage: "https://kymedcan.ky.gov/",
    checklistItems: ["Licensing","Testing","Packaging","Seed-to-sale","Dispensing"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Louisiana": {
    program: "https://ldh.la.gov/page/medical-marijuana",
    patientPortal: "Requires prescription from regular doctor",
    businessPortal: "https://ldh.la.gov/assets/oph/Center-EH/sanitarian/fooddrug/marijuana/Marijuana-Retailer-Plans-Review-Questionnaire---1-26.Fillable.pdf",
    guide: "",
    resources: "https://www.mpp.org/states/louisiana/?state=LA",
    abbreviation: "LA",
    adultUseStatus: "No",
    medicalStatus: "Yes",
    regulator: "Louisiana Department of Health",
    compliancePage: "https://ldh.la.gov/page/medical-marijuana",
    checklistItems: ["Medical cultivation/processing","Testing","Product rules","Retailer permits"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Maine": {
    program: "https://www.maine.gov/dafs/ocp/medical-use/applications-forms/registryidentificationcard-instructions",
    patientPortal: "https://licensing.web.maine.gov/cgi-bin/online/licensing/begin.pl?board_number=421",
    businessPortal: "https://licensing.web.maine.gov/cgi-bin/online/licensing/begin.pl?board_number=421",
    guide: "https://www.maine.gov/dafs/ocp/medical-use/applications-forms/registryidentificationcard-instructions",
    resources: "https://www.mpp.org/states/maine/?state=ME",
    abbreviation: "ME",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Maine Office of Cannabis Policy",
    compliancePage: "https://www.maine.gov/dafs/ocp/",
    checklistItems: ["License","Testing","Packaging","Labeling","Labor","Tax"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Maryland": {
    program: "https://cannabis.maryland.gov/Pages/Medical_Cannabis.aspx",
    patientPortal: "https://cannabis.maryland.gov/Pages/patients.aspx",
    businessPortal: "https://cannabis.maryland.gov/Pages/Industry_Licensees_and_Registrants.aspx",
    guide: "https://cannabis.maryland.gov/Documents/Infographics/DesignateCaregiver_Patient_Process.pdf",
    resources: "https://www.mpp.org/states/maryland/?state=MD",
    abbreviation: "MD",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Maryland Cannabis Administration",
    compliancePage: "https://cannabis.maryland.gov/",
    checklistItems: ["Licensing","Testing","Advertising","Track-and-trace","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Massachusetts": {
    program: "https://masscannabiscontrol.com/new-patients/register-as-a-new-patient/",
    patientPortal: "https://patient.massciportal.com/mmj-patient/login",
    businessPortal: "https://masscannabiscontrol.com/license-types/",
    guide: "",
    resources: "https://www.mpp.org/states/massachusetts/?state=MA",
    abbreviation: "MA",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Massachusetts Cannabis Control Commission",
    compliancePage: "https://masscannabiscontrol.com/",
    checklistItems: ["License","Testing","Security","Recalls","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Michigan": {
    program: "https://www.michigan.gov/cra/sections/mmp",
    patientPortal: "https://aca-prod.accela.com/MIMM/Default.aspx",
    businessPortal: "https://www.michigan.gov/cra/sections/mmp",
    guide: "",
    resources: "https://www.mpp.org/states/michigan/?state=MI",
    abbreviation: "MI",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Michigan Cannabis Regulatory Agency",
    compliancePage: "https://www.michigan.gov/cra/",
    checklistItems: ["License","Testing","METRC","Packaging","Advertising"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Minnesota": {
    program: "https://mn.gov/ocm/businesses/licensing/license-types/",
    patientPortal: "https://cannabis.web.health.state.mn.us/",
    businessPortal: "https://mn.gov/ocm/businesses/licensing/license-types/",
    guide: "https://www.mda.state.mn.us/plants/hemp/firsttimeapplicants",
    resources: "https://www.mpp.org/states/minnesota/?state=MN",
    abbreviation: "MN",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Minnesota Office of Cannabis Management",
    compliancePage: "https://mn.gov/ocm/",
    checklistItems: ["Licensing","Testing","Packaging","Local approvals"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Mississippi": {
    program: "https://ms-doh-public.nls.egov.com/login",
    patientPortal: "https://www.mmcp.ms.gov/patients-caregivers",
    businessPortal: "https://www.mmcp.ms.gov/businesses",
    guide: "https://msdh.ms.gov/page/30,0,425.html",
    resources: "https://www.mpp.org/states/mississippi/?state=MS",
    abbreviation: "MS",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "Mississippi Medical Cannabis Program",
    compliancePage: "https://www.mmcp.ms.gov/",
    checklistItems: ["Medical licensing","Testing","Labeling","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Missouri": {
    program: "https://mo-public.mycomplia.com/login",
    patientPortal: "https://mo-public.mycomplia.com/register",
    businessPortal: "https://mo-public.mycomplia.com/register",
    guide: "",
    resources: "https://www.mpp.org/states/missouri/?state=MO",
    abbreviation: "MO",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Missouri Division of Cannabis Regulation",
    compliancePage: "https://health.mo.gov/safety/cannabis/",
    checklistItems: ["License","Testing","Packaging","Track-and-trace","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Montana": {
    program: "https://revenue.mt.gov/",
    patientPortal: "https://tap.dor.mt.gov/_/",
    businessPortal: "https://tap.dor.mt.gov/",
    guide: "",
    resources: "https://www.mpp.org/states/montana/?state=MT",
    abbreviation: "MT",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Montana Cannabis Control Division",
    compliancePage: "https://revenue.mt.gov/",
    checklistItems: ["License","Testing","Labeling","Inventory","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Nebraska": {
    program: "https://lcc.nebraska.gov/medical-cannabis/medical-cannabis-commission-how-apply",
    patientPortal: "https://lcc.nebraska.gov/medical-cannabis/medical-cannabis-commission-how-apply",
    businessPortal: "https://lcc.nebraska.gov/medical-cannabis/medical-cannabis-commission-how-apply",
    guide: "",
    resources: "https://www.mpp.org/states/nebraska/?state=NE",
    abbreviation: "NE",
    adultUseStatus: "Just legalized Mar/Apr 2026",
    medicalStatus: "No comprehensive program",
    regulator: "Nebraska Medical Cannabis Commission",
    compliancePage: "https://lcc.nebraska.gov/medical-cannabis/",
    checklistItems: ["Cultivator licensing priority","Residency requirements","Background checks"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "Nevada": {
    program: "https://mmportal.nv.gov/PatientRegistryOnline/PatientRegistryOLCreateLogin",
    patientPortal: "https://mmportal.nv.gov/PatientRegistryOnline/PatientRegistryOLCreateLogin",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/nevada/?state=NV",
    abbreviation: "NV",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Nevada Cannabis Compliance Board",
    compliancePage: "https://ccb.nv.gov/",
    checklistItems: ["License","Testing","Packaging","Security","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "New Hampshire": {
    program: "https://www.dhhs.nh.gov/programs-services/population-health/therapeutic-cannabis/therapeutic-cannabis-applications-and",
    patientPortal: "https://www.dhhs.nh.gov/sites/g/files/ehbemt476/files/documents/2021-11/tcp-applicationpatient.pdf",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/new-hampshire/?state=NH",
    abbreviation: "NH",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "New Hampshire DHHS",
    compliancePage: "https://www.dhhs.nh.gov/programs-services/population-health/therapeutic-cannabis/",
    checklistItems: ["Medical cultivation/dispensary rules","Testing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "New Jersey": {
    program: "https://www.nj.gov/cannabis/medicinalcannabis/patient-registration/",
    patientPortal: "https://njmcp.crc.nj.gov/web/#/home/createAdultPatientUser",
    businessPortal: "https://www.nj.gov/cannabis/businesses/recreational/license-application-process/",
    guide: "",
    resources: "https://www.mpp.org/states/new-jersey/?state=NJ",
    abbreviation: "NJ",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "New Jersey Cannabis Regulatory Commission",
    compliancePage: "https://www.nj.gov/cannabis/",
    checklistItems: ["License","Testing","Labeling","Labor","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "New Mexico": {
    program: "https://www.rld.nm.gov/cannabis/licensing/new-applications/apply-for-license/",
    patientPortal: "https://www.rld.nm.gov/cannabis/licensing/new-applications/",
    businessPortal: "https://www.rld.nm.gov/cannabis/licensing/apply-renew-a-cannabis-license/",
    guide: "",
    resources: "https://www.mpp.org/states/new-mexico/?state=NM",
    abbreviation: "NM",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "New Mexico Cannabis Control Division",
    compliancePage: "https://www.rld.nm.gov/cannabis/",
    checklistItems: ["License","Testing","Packaging","Track-and-trace"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "New York": {
    program: "https://cannabis.ny.gov/medical-cannabis-program-applications",
    patientPortal: "https://cannabis.ny.gov/patients",
    businessPortal: "https://cannabis.ny.gov/licensing",
    guide: "",
    resources: "https://www.mpp.org/states/new-york/?state=NY",
    abbreviation: "NY",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "New York Office of Cannabis Management",
    compliancePage: "https://cannabis.ny.gov/",
    checklistItems: ["License","Testing","Labeling","Marketing","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "North Carolina": {
    program: "https://northcarolinastatecannabis.org/medical",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/north-carolina/?state=NC",
    abbreviation: "NC",
    adultUseStatus: "No",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "North Dakota": {
    program: "https://mmregistration.health.nd.gov/",
    patientPortal: "https://mmregistration.health.nd.gov/",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/north-dakota/?state=ND",
    abbreviation: "ND",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "North Dakota DHHS",
    compliancePage: "https://mmregistration.health.nd.gov/",
    checklistItems: ["Medical licensing","Testing","Dispensing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Ohio": {
    program: "https://com.ohio.gov/divisions-and-programs/cannabis-control/patients-caregivers/obtain-medical-marijuana",
    patientPortal: "https://com.ohio.gov/divisions-and-programs/cannabis-control/patients-caregivers/patient-and-caregiver-registry",
    businessPortal: "https://com.ohio.gov/divisions-and-programs/cannabis-control",
    guide: "",
    resources: "https://www.mpp.org/states/ohio/?state=OH",
    abbreviation: "OH",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Ohio Division of Cannabis Control",
    compliancePage: "https://com.ohio.gov/divisions-and-programs/cannabis-control",
    checklistItems: ["License","Testing","Packaging","Track-and-trace","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Oklahoma": {
    program: "https://oklahoma.gov/omma/apply.html",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/oklahoma/?state=OK",
    abbreviation: "OK",
    adultUseStatus: "No",
    medicalStatus: "Yes",
    regulator: "Oklahoma Medical Marijuana Authority",
    compliancePage: "https://oklahoma.gov/omma/businesses/inspections-and-compliance.html",
    checklistItems: ["Post-approval checklist","OBNDD registration","METRC","Tax compliance","Fire/safety","Water compliance"],
    complianceSource: "https://oklahoma.gov/omma/businesses/inspections-and-compliance.html",
    biddingPortals: {
      state: "https://www.ok.gov/dcs/solicit/app/contractSearch.php",
      city: "https://www.okc.gov/Infrastructure-Development/Bids-Auctions-and-Sales/Bidding"
    }
  },
  "Oregon": {
    program: "https://www.oregon.gov/oha/ph/diseasesconditions/chronicdisease/medicalmarijuanaprogram/pages/forms.aspx",
    patientPortal: "https://www.oregon.gov/oha/ph/diseasesconditions/chronicdisease/medicalmarijuanaprogram/pages/forms.aspx#online",
    businessPortal: "https://ommpsystem.oregon.gov/",
    guide: "",
    resources: "https://www.mpp.org/states/oregon/?state=OR",
    abbreviation: "OR",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Oregon Liquor and Cannabis Commission",
    compliancePage: "https://www.oregon.gov/olcc/",
    checklistItems: ["License","Testing","Packaging","Labeling","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Pennsylvania": {
    program: "https://www.pa.gov/services/health/register-for-the-medical-marijuana-program",
    patientPortal: "https://padohmmp.custhelp.com/app/login",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/pennsylvania/?state=PA",
    abbreviation: "PA",
    adultUseStatus: "No",
    medicalStatus: "Yes",
    regulator: "Pennsylvania Department of Health",
    compliancePage: "https://www.pa.gov/services/health/register-for-the-medical-marijuana-program",
    checklistItems: ["Medical licensing","Testing","Dispensing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Rhode Island": {
    program: "https://health.ri.gov/medical-marijuana/information/patients-caregivers",
    patientPortal: "https://cannabislicensing.ri.gov/ricannabis/s/login/",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/rhode-island/?state=RI",
    abbreviation: "RI",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Rhode Island Cannabis Control Commission",
    compliancePage: "https://dbr.ri.gov/cannabis/",
    checklistItems: ["License","Testing","Labeling","Tax","Inspections"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "South Carolina": {
    program: "https://southcarolinastatecannabis.org/medical",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/south-carolina/?state=SC",
    abbreviation: "SC",
    adultUseStatus: "No",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "South Dakota": {
    program: "https://medcannabisapplication.sd.gov/",
    patientPortal: "https://medcannabis.sd.gov/",
    businessPortal: "https://medcannabis.sd.gov/Establishments/Forms.aspx",
    guide: "",
    resources: "https://www.mpp.org/states/south-dakota/?state=SD",
    abbreviation: "SD",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "South Dakota Department of Health",
    compliancePage: "https://medcannabis.sd.gov/",
    checklistItems: ["Medical licensing","Testing","Dispensing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Tennessee": {
    program: "https://www.tn.gov/agriculture/businesses/hemp/hemp-derived-cannabinoids/hemp-derived-cannabinoids-licensing.html",
    patientPortal: "",
    businessPortal: "https://www.tn.gov/abc.html",
    guide: "",
    resources: "https://www.mpp.org/states/tennessee/?state=TN",
    abbreviation: "TN",
    adultUseStatus: "No",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "Texas": {
    program: "https://www.texas.gov/health-services/texas-medical-marijuana/",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/texas/?state=TX",
    abbreviation: "TX",
    adultUseStatus: "No/limited",
    medicalStatus: "Limited",
    regulator: "Texas Department of Public Safety",
    compliancePage: "https://www.texas.gov/health-services/texas-medical-marijuana/",
    checklistItems: ["Low-THC product rules","Licensing","Testing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Utah": {
    program: "https://medicalcannabis.utah.gov/patients/apply-for-patient-card/",
    patientPortal: "https://id.utah.gov/login",
    businessPortal: "https://medicalcannabis.utah.gov/patients/apply-for-patient-card/",
    guide: "",
    resources: "https://www.mpp.org/states/utah/?state=UT",
    abbreviation: "UT",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "Utah Department of Health and Human Services",
    compliancePage: "https://medicalcannabis.utah.gov/",
    checklistItems: ["Medical licensing","Testing","Labeling","Dispensing"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Vermont": {
    program: "https://ccb.vermont.gov/med-forms",
    patientPortal: "https://ccb.vermont.gov/forms",
    businessPortal: "https://ccb.vermont.gov/applications",
    guide: "",
    resources: "https://www.mpp.org/states/vermont/?state=VT",
    abbreviation: "VT",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Vermont Cannabis Control Board",
    compliancePage: "https://ccb.vermont.gov/",
    checklistItems: ["License","Testing","Packaging","Labeling","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Virginia": {
    program: "https://cca.virginia.gov/medicalcannabis",
    patientPortal: "https://cca.virginia.gov/medicalcannabis/patients",
    businessPortal: "https://cca.virginia.gov/medicalcannabis/patients",
    guide: "",
    resources: "https://www.mpp.org/states/virginia/?state=VA",
    abbreviation: "VA",
    adultUseStatus: "Yes/limited retail",
    medicalStatus: "Yes",
    regulator: "Virginia Cannabis Control Authority",
    compliancePage: "https://cca.virginia.gov/",
    checklistItems: ["License framework","Retail status","Labeling","Records"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "Washington": {
    program: "https://doh.wa.gov/you-and-your-family/cannabis/medical-cannabis/patient-information",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/washington/?state=WA",
    abbreviation: "WA",
    adultUseStatus: "Yes",
    medicalStatus: "Yes",
    regulator: "Washington State Liquor and Cannabis Board",
    compliancePage: "https://lcb.wa.gov/",
    checklistItems: ["License","Testing","Packaging","Traceability","Taxes"],
    complianceSource: "https://www.nsc.org/cannabis-regulations"
  },
  "West Virginia": {
    program: "https://omc.wv.gov/patient-application/Pages/default.aspx",
    patientPortal: "https://omc.wv.gov/patients/Pages/default.aspx",
    businessPortal: "https://omc.wv.gov/industry/application/Pages/default.aspx",
    guide: "",
    resources: "https://www.mpp.org/states/west-virginia/?state=WV",
    abbreviation: "WV",
    adultUseStatus: "No/limited",
    medicalStatus: "Yes",
    regulator: "West Virginia Office of Medical Cannabis",
    compliancePage: "https://omc.wv.gov/",
    checklistItems: ["Medical licensing","Testing","Dispensing","Records"],
    complianceSource: "https://www.ncsl.org/health/state-medical-cannabis-laws"
  },
  "Wisconsin": {
    program: "https://docs.legis.wisconsin.gov/2025/related/proposals/sb534",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/wisconsin/?state=WI",
    abbreviation: "WI",
    adultUseStatus: "Just legalized March 2026",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework yet"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  },
  "Wyoming": {
    program: "https://wyomingcannabis.org/medical",
    patientPortal: "",
    businessPortal: "",
    guide: "",
    resources: "https://www.mpp.org/states/wyoming/?state=WY",
    abbreviation: "WY",
    adultUseStatus: "No",
    medicalStatus: "No comprehensive program",
    regulator: "State law only",
    compliancePage: "",
    checklistItems: ["No operational cannabis business framework"],
    complianceSource: "https://en.wikipedia.org/wiki/Legality_of_cannabis_by_U.S._jurisdiction"
  }
};

// Helper: find state by name or abbreviation
export const findState = (query: string): string | null => {
  const lower = query.toLowerCase();
  for (const [name, data] of Object.entries(STATE_RESOURCES)) {
    if (lower.includes(name.toLowerCase())) return name;
    if (data.abbreviation && lower === data.abbreviation.toLowerCase()) return name;
  }
  return null;
};

// Helper: get all state names
export const getStateNames = (): string[] => Object.keys(STATE_RESOURCES);

// Helper: count states with active patient portals
export const getActiveStates = (): string[] =>
  Object.entries(STATE_RESOURCES)
    .filter(([, d]) => d.patientPortal && !d.patientPortal.includes('Login Required') && !d.patientPortal.includes('Requires'))
    .map(([name]) => name);
